//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTM_Nigeria.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(iom_profile))]
    [KnownType(typeof(iom_ward_profile))]
    [KnownType(typeof(iom_group_assessment_1))]
    public partial class iom_researchers
    {
        #region Primitive Properties
        [DataMember]
        public virtual int id
        {
            get;
            set;
        }
        [DataMember]
        public virtual string researcher_name
        {
            get;
            set;
        }
        [DataMember]
        public virtual string researcher_tel
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<iom_profile> iom_profile
        {
            get
            {
                if (_iom_profile == null)
                {
                    var newCollection = new FixupCollection<iom_profile>();
                    newCollection.CollectionChanged += Fixupiom_profile;
                    _iom_profile = newCollection;
                }
                return _iom_profile;
            }
            set
            {
                if (!ReferenceEquals(_iom_profile, value))
                {
                    var previousValue = _iom_profile as FixupCollection<iom_profile>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_profile;
                    }
                    _iom_profile = value;
                    var newValue = value as FixupCollection<iom_profile>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_profile;
                    }
                }
            }
        }
        private ICollection<iom_profile> _iom_profile;
        
    
        [DataMember]
        public virtual ICollection<iom_ward_profile> iom_ward_profile
        {
            get
            {
                if (_iom_ward_profile == null)
                {
                    var newCollection = new FixupCollection<iom_ward_profile>();
                    newCollection.CollectionChanged += Fixupiom_ward_profile;
                    _iom_ward_profile = newCollection;
                }
                return _iom_ward_profile;
            }
            set
            {
                if (!ReferenceEquals(_iom_ward_profile, value))
                {
                    var previousValue = _iom_ward_profile as FixupCollection<iom_ward_profile>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_ward_profile;
                    }
                    _iom_ward_profile = value;
                    var newValue = value as FixupCollection<iom_ward_profile>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_ward_profile;
                    }
                }
            }
        }
        private ICollection<iom_ward_profile> _iom_ward_profile;
        
    
        [DataMember]
        public virtual ICollection<iom_group_assessment_1> iom_group_assessment_1
        {
            get
            {
                if (_iom_group_assessment_1 == null)
                {
                    var newCollection = new FixupCollection<iom_group_assessment_1>();
                    newCollection.CollectionChanged += Fixupiom_group_assessment_1;
                    _iom_group_assessment_1 = newCollection;
                }
                return _iom_group_assessment_1;
            }
            set
            {
                if (!ReferenceEquals(_iom_group_assessment_1, value))
                {
                    var previousValue = _iom_group_assessment_1 as FixupCollection<iom_group_assessment_1>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_group_assessment_1;
                    }
                    _iom_group_assessment_1 = value;
                    var newValue = value as FixupCollection<iom_group_assessment_1>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_group_assessment_1;
                    }
                }
            }
        }
        private ICollection<iom_group_assessment_1> _iom_group_assessment_1;

        #endregion

        #region Association Fixup
    
        private void Fixupiom_profile(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_profile item in e.NewItems)
                {
                    item.iom_researchers = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_profile item in e.OldItems)
                {
                    if (ReferenceEquals(item.iom_researchers, this))
                    {
                        item.iom_researchers = null;
                    }
                }
            }
        }
    
        private void Fixupiom_ward_profile(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_ward_profile item in e.NewItems)
                {
                    item.iom_researchers = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_ward_profile item in e.OldItems)
                {
                    if (ReferenceEquals(item.iom_researchers, this))
                    {
                        item.iom_researchers = null;
                    }
                }
            }
        }
    
        private void Fixupiom_group_assessment_1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_group_assessment_1 item in e.NewItems)
                {
                    item.iom_researchers = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_group_assessment_1 item in e.OldItems)
                {
                    if (ReferenceEquals(item.iom_researchers, this))
                    {
                        item.iom_researchers = null;
                    }
                }
            }
        }

        #endregion

    }
}
