//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTM_Nigeria.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(iom_informants))]
    public partial class lkp_Sex
    {
        #region Primitive Properties
        [DataMember]
        public virtual string id
        {
            get;
            set;
        }
        [DataMember]
        public virtual string sex
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<iom_informants> iom_informants
        {
            get
            {
                if (_iom_informants == null)
                {
                    var newCollection = new FixupCollection<iom_informants>();
                    newCollection.CollectionChanged += Fixupiom_informants;
                    _iom_informants = newCollection;
                }
                return _iom_informants;
            }
            set
            {
                if (!ReferenceEquals(_iom_informants, value))
                {
                    var previousValue = _iom_informants as FixupCollection<iom_informants>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_informants;
                    }
                    _iom_informants = value;
                    var newValue = value as FixupCollection<iom_informants>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_informants;
                    }
                }
            }
        }
        private ICollection<iom_informants> _iom_informants;

        #endregion

        #region Association Fixup
    
        private void Fixupiom_informants(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_informants item in e.NewItems)
                {
                    item.lkp_Sex = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_informants item in e.OldItems)
                {
                    if (ReferenceEquals(item.lkp_Sex, this))
                    {
                        item.lkp_Sex = null;
                    }
                }
            }
        }

        #endregion

    }
}
