//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTM_Nigeria.Models
{
    [DataContract(IsReference = true)]
    public partial class view_error_check_Camp_with_No_Figues_In_B2F
    {
        #region Primitive Properties
        [DataMember]
        public virtual int phase
        {
            get;
            set;
        }
        [DataMember]
        public virtual string state_name
        {
            get;
            set;
        }
        [DataMember]
        public virtual string lga_name
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ward_name
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> hhs_Ward
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> inds_Ward
        {
            get;
            set;
        }

        #endregion

    }
}
