//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTM_Nigeria.Models
{
    [DataContract(IsReference = true)]
    public partial class view_estimate_hhs_Inds_Age_Breakdown
    {
        #region Primitive Properties
        [DataMember]
        public virtual int phase
        {
            get;
            set;
        }
        [DataMember]
        public virtual string state_code
        {
            get;
            set;
        }
        [DataMember]
        public virtual string state_name
        {
            get;
            set;
        }
        [DataMember]
        public virtual string lga_code
        {
            get;
            set;
        }
        [DataMember]
        public virtual string lga_name
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ward_code
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ward_name
        {
            get;
            set;
        }
        [DataMember]
        public virtual int estimate_hh_Ward
        {
            get;
            set;
        }
        [DataMember]
        public virtual int estimate_Ind_Ward
        {
            get;
            set;
        }
        [DataMember]
        public virtual int id
        {
            get;
            set;
        }
        [DataMember]
        public virtual string sex
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Age_group
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> inds
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> hhs
        {
            get;
            set;
        }

        #endregion

    }
}
