//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace DTM_Nigeria.Models
{
    [DataContract(IsReference = true)]
    public partial class view_estimate_hhs_Inds_per_Wards
    {
        #region Primitive Properties
        [DataMember]
        public virtual int phase
        {
            get;
            set;
        }
        [DataMember]
        public virtual string state_code
        {
            get;
            set;
        }
        [DataMember]
        public virtual string state_name
        {
            get;
            set;
        }
        [DataMember]
        public virtual string lga_code
        {
            get;
            set;
        }
        [DataMember]
        public virtual string lga_name
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ward_code
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ward_name
        {
            get;
            set;
        }
        [DataMember]
        public virtual int id
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> estimate_hh_Ward
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> estimate_Ind_Ward
        {
            get;
            set;
        }
        [DataMember]
        public virtual string location_type
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Year
        {
            get;
            set;
        }
        [DataMember]
        public virtual int idp_category
        {
            get;
            set;
        }
        [DataMember]
        public virtual string majority_stateoforigin
        {
            get;
            set;
        }
        [DataMember]
        public virtual string state_orig
        {
            get;
            set;
        }
        [DataMember]
        public virtual string majority_lgaoforigin
        {
            get;
            set;
        }
        [DataMember]
        public virtual string lga_orig
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> reason_insurgency_YesNo
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> reason_insurg_hh
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> reason_insurg_ind
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> reason_clash_YesNo
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> reason_clash_hh
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> reason_clash_ind
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> reason_disaster_YesNo
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> reason_disaster_hh
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> reason_disaster_ind
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> reason_others_YesNo
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> reason_others_hh
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> reason_others_ind
        {
            get;
            set;
        }

        #endregion

    }
}
