//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class iom_organizations
    {
        public iom_organizations()
        {
            this.iom_b1f_organizations_assisting = new HashSet<iom_b1f_organizations_assisting>();
            this.iom_b2f_organizations_assisting = new HashSet<iom_b2f_organizations_assisting>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> type { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<iom_b1f_organizations_assisting> iom_b1f_organizations_assisting { get; set; }
        public virtual ICollection<iom_b2f_organizations_assisting> iom_b2f_organizations_assisting { get; set; }
        public virtual lkp_Organization lkp_Organization { get; set; }
    }
    
}
