//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using DTM_Nigeria.Validation;
using System.ComponentModel.DataAnnotations;

namespace DTM_Nigeria.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(iom_group_assessment_1))]
    [KnownType(typeof(lkp_ChildProIncident))]
    [KnownType(typeof(lkp_GBV))]
    [KnownType(typeof(lkp_HealthProblem))]
    [KnownType(typeof(lkp_Incident))]
    [KnownType(typeof(lkp_Intention))]
    [KnownType(typeof(lkp_Lga))]
    [KnownType(typeof(lkp_NeededNFI))]
    [KnownType(typeof(lkp_Opportunity))]
    [KnownType(typeof(lkp_Relationship_Type))]
    [KnownType(typeof(lkp_TravelLocation))]
    [KnownType(typeof(lkp_Ward))]
    [KnownType(typeof(lkp_YesNo))]
    public partial class iom_group_assessment_2
    {
        #region Primitive Properties
        [DataMember]
        public virtual int id
        {
            get { return _id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_id != value)
                    {
                        if (iom_group_assessment_1 != null && iom_group_assessment_1.id != value)
                        {
                            iom_group_assessment_1 = null;
                        }
                        _id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _id;
        [DataMember]
        [Required(ErrorMessage = "*")]
        public virtual Nullable<int> member_disp_p1_YesNo
        {
            get;
            set;
        }
        [DataMember]
        [RequiredIf("member_disp_p1_YesNo", 1, "*")]
        public virtual Nullable<int> how_many_time_disp
        {
            get;
            set;
        }


        [RequiredIf("member_disp_p1_YesNo", 1, "*")]
        public string state { get; set; }

        [DataMember]
        [RequiredIf("member_disp_p1_YesNo", 1, "*")]
        public virtual string if_yes_lga_maj
        {
            get { return _if_yes_lga_maj; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_if_yes_lga_maj != value)
                    {
                        if (lkp_Lga != null && lkp_Lga.lga_code != value)
                        {
                            lkp_Lga = null;
                        }
                        _if_yes_lga_maj = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private string _if_yes_lga_maj;
        [DataMember]
        [RequiredIf("member_disp_p1_YesNo", 1, "*")]
        public virtual string if_yes_ward_maj
        {
            get { return _if_yes_ward_maj; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_if_yes_ward_maj != value)
                    {
                        if (lkp_Ward != null && lkp_Ward.ward_code != value)
                        {
                            lkp_Ward = null;
                        }
                        _if_yes_ward_maj = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private string _if_yes_ward_maj;
        [DataMember]
        [Required(ErrorMessage = "*")]
        public virtual Nullable<int> intention_of_majority
        {
            get { return _intention_of_majority; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_intention_of_majority != value)
                    {
                        if (lkp_Intention != null && lkp_Intention.id != value)
                        {
                            lkp_Intention = null;
                        }
                        _intention_of_majority = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _intention_of_majority;
        [DataMember]
        [RegularExpression("^[1-9]+[0-9]*", ErrorMessage = "number>0")]
        public virtual Nullable<int> v_unaccompanied_children
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[1-9]+[0-9]*", ErrorMessage = "number>0")]
        public virtual Nullable<int> v_separated_children
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> v_children_at_risk
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[1-9]+[0-9]*", ErrorMessage = "number>0")]
        public virtual Nullable<int> v_minor_hh
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[1-9]+[0-9]*", ErrorMessage = "number>0")]
        public virtual Nullable<int> v_female_hh
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[1-9]+[0-9]*", ErrorMessage = "number>0")]
        public virtual Nullable<int> v_women_at_risk
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> v_older_at_risk
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> v_single_parent
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[1-9]+[0-9]*", ErrorMessage = "number>0")]
        public virtual Nullable<int> v_physical_disability
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[1-9]+[0-9]*", ErrorMessage = "number>0")]
        public virtual Nullable<int> v_mental_disability
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[1-9]+[0-9]*", ErrorMessage = "number>0")]
        public virtual Nullable<int> v_serious_med_condition
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> v_missing_relatives
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> v_surviror_at_risk_of_viol
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> v_profile_based_risk
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[1-9]+[0-9]*", ErrorMessage = "number>0")]
        public virtual Nullable<int> v_other
        {
            get;
            set;
        }
        [DataMember]
        public virtual string v_specify
        {
            get;
            set;
        }
        [DataMember]
        [Range(1, 5, ErrorMessage = "1-5")]
        public virtual Nullable<int> need_water
        {
            get;
            set;
        }
        [DataMember]
        [Range(1, 5, ErrorMessage = "1-5")]
        public virtual Nullable<int> need_food
        {
            get;
            set;
        }
        [DataMember]
        [Range(1, 5, ErrorMessage = "1-5")]
        public virtual Nullable<int> need_health
        {
            get;
            set;
        }

        public bool b_need_other { get { return need_other > 0; } set { if (value)need_other = null; } }
        public bool b_need_other2 { get { return (!string.IsNullOrEmpty(need_specify)); } set { if (value)need_specify = null; } }

        [DataMember]
        [Range(1, 5, ErrorMessage = "1-5")]
        [RequiredIf("b_need_other2", true, "*")]
        public virtual Nullable<int> need_other
        {
            get;
            set;
        }
        [DataMember]
        [RequiredIf("b_need_other", true, "*")]
        public virtual string need_specify
        {
            get;
            set;
        }
        [DataMember]
        [Range(1, 5, ErrorMessage = "1-5")]
        public virtual Nullable<int> need_sanitation
        {
            get;
            set;
        }
        [DataMember]
        [Range(1, 5, ErrorMessage = "1-5")]
        public virtual Nullable<int> need_shelter
        {
            get;
            set;
        }
        [DataMember]
        [Range(1, 5, ErrorMessage = "1-5")]
        public virtual Nullable<int> need_education
        {
            get;
            set;
        }
        [DataMember]
        [Range(1, 5, ErrorMessage = "1-5")]
        public virtual Nullable<int> need_access_icome
        {
            get;
            set;
        }
        [DataMember]
        [Range(1, 5, ErrorMessage = "1-5")]
        public virtual Nullable<int> need_lhelp
        {
            get;
            set;
        }
        [DataMember]
        [Range(1, 5, ErrorMessage = "1-5")]
        public virtual Nullable<int> need_nfi
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> health_care_service_YesNo
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> health_most_prevalent
        {
            get { return _health_most_prevalent; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_health_most_prevalent != value)
                    {
                        if (lkp_HealthProblem != null && lkp_HealthProblem.id != value)
                        {
                            lkp_HealthProblem = null;
                        }
                        _health_most_prevalent = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _health_most_prevalent;
        [DataMember]
        public virtual string health_specify
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> sec_people_feel_safe_YesNo
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> sec_relationship_idp_comm
        {
            get { return _sec_relationship_idp_comm; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_sec_relationship_idp_comm != value)
                    {
                        if (lkp_Relationship_Type != null && lkp_Relationship_Type.id != value)
                        {
                            lkp_Relationship_Type = null;
                        }
                        _sec_relationship_idp_comm = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _sec_relationship_idp_comm;
        [DataMember]
        public virtual Nullable<System.DateTime> create_time
        {
            get;
            set;
        }
        [DataMember]
        public virtual string created_by
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> update_time
        {
            get;
            set;
        }
        [DataMember]
        public virtual string updated_by
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[1-9]+[0-9]*", ErrorMessage = "number>0")]
        public virtual Nullable<int> v_pregnant_women
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[1-9]+[0-9]*", ErrorMessage = "number>0")]
        public virtual Nullable<int> v_breastfeeding_mother
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[1-9]+[0-9]*", ErrorMessage = "number>0")]
        public virtual Nullable<int> v_male_hh
        {
            get;
            set;
        }
        [DataMember]
        [Required(ErrorMessage="*")]
        public virtual Nullable<int> protect_people_feel_safe_YesNo
        {
            get { return _protect_people_feel_safe_YesNo; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_protect_people_feel_safe_YesNo != value)
                    {
                        if (lkp_YesNo != null && lkp_YesNo.id != value)
                        {
                            lkp_YesNo = null;
                        }
                        _protect_people_feel_safe_YesNo = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _protect_people_feel_safe_YesNo;
        [DataMember]
        [RequiredIf("protect_people_feel_safe_YesNo", 4, "*")]
        public virtual string protect_people_feel_safe_ifNoAns
        {
            get;
            set;
        }
        [DataMember]
        [Required(ErrorMessage = "*")]
        public virtual Nullable<int> protect_common_incident
        {
            get { return _protect_common_incident; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_protect_common_incident != value)
                    {
                        if (lkp_Incident != null && lkp_Incident.id != value)
                        {
                            lkp_Incident = null;
                        }
                        _protect_common_incident = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _protect_common_incident;
        [DataMember]
        [RequiredIf("protect_common_incident", 9, "*")]
        public virtual string protect_common_in_ifOther
        {
            get;
            set;
        }
        [DataMember]
        [RequiredIf("protect_common_incident", 10, "*")]
        public virtual string protect_common_in_ifNoAns
        {
            get;
            set;
        }
        [DataMember]
        [Required(ErrorMessage = "*")]
        public virtual Nullable<int> protect_common_GBV
        {
            get { return _protect_common_GBV; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_protect_common_GBV != value)
                    {
                        if (lkp_GBV != null && lkp_GBV.id != value)
                        {
                            lkp_GBV = null;
                        }
                        _protect_common_GBV = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _protect_common_GBV;
        [DataMember]
        [RequiredIf("protect_common_GBV", 8, "*")]
        public virtual string protect_common_GBV_ifOther
        {
            get;
            set;
        }
        [DataMember]
        [RequiredIf("protect_common_GBV", 9, "*")]
        public virtual string protect_common_GBV_ifNoAns
        {
            get;
            set;
        }
        [DataMember]
        [Required(ErrorMessage = "*")]
        public virtual Nullable<int> protect_common_child_p_incident
        {
            get { return _protect_common_child_p_incident; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_protect_common_child_p_incident != value)
                    {
                        if (lkp_ChildProIncident != null && lkp_ChildProIncident.id != value)
                        {
                            lkp_ChildProIncident = null;
                        }
                        _protect_common_child_p_incident = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _protect_common_child_p_incident;
        [DataMember]
        [RequiredIf("protect_common_child_p_incident", 11, "*")]
        public virtual string protect_common_child_p_incident_ifOther
        {
            get;
            set;
        }
        [DataMember]
        [Required(ErrorMessage = "*")]
        public virtual Nullable<int> protect_travel_oic_YesNo
        {
            get { return _protect_travel_oic_YesNo; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_protect_travel_oic_YesNo != value)
                    {
                        if (lkp_YesNo1 != null && lkp_YesNo1.id != value)
                        {
                            lkp_YesNo1 = null;
                        }
                        _protect_travel_oic_YesNo = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _protect_travel_oic_YesNo;
        [DataMember]
        [RequiredIf("protect_travel_oic_YesNo", 1, "*")]
        public virtual Nullable<int> protect_travel_oic_ifYes_where
        {
            get { return _protect_travel_oic_ifYes_where; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_protect_travel_oic_ifYes_where != value)
                    {
                        if (lkp_TravelLocation != null && lkp_TravelLocation.id != value)
                        {
                            lkp_TravelLocation = null;
                        }
                        _protect_travel_oic_ifYes_where = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _protect_travel_oic_ifYes_where;
        [DataMember]
        [RequiredIf("protect_travel_oic_YesNo", 1, "*")]
        public virtual Nullable<int> protect_travel_oic_ifYes_what
        {
            get { return _protect_travel_oic_ifYes_what; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_protect_travel_oic_ifYes_what != value)
                    {
                        if (lkp_Opportunity != null && lkp_Opportunity.id != value)
                        {
                            lkp_Opportunity = null;
                        }
                        _protect_travel_oic_ifYes_what = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _protect_travel_oic_ifYes_what;
        [DataMember]
        public virtual Nullable<int> shelter_num_people
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> shelter_num_hc
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> shelter_num_rh
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> shelter_num_ms
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> shelter_num_es
        {
            get;
            set;
        }
        [DataMember]
        [Required(ErrorMessage = "*")]
        public virtual Nullable<int> shelter_mn_nfi
        {
            get { return _shelter_mn_nfi; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_shelter_mn_nfi != value)
                    {
                        if (lkp_NeededNFI != null && lkp_NeededNFI.id != value)
                        {
                            lkp_NeededNFI = null;
                        }
                        _shelter_mn_nfi = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _shelter_mn_nfi;
        [DataMember]
        [RequiredIf("shelter_mn_nfi", 5, "*")]
        public virtual string shelter_mn_other
        {
            get;
            set;
        }

        //public bool b_v_unaccompanied_children { get { return v_unaccompanied_children == 1; } set { if (value) v_unaccompanied_children = 1; else v_unaccompanied_children = 2; } }
        //public bool b_v_separated_children { get { return v_separated_children == 1; } set { if (value) v_separated_children = 1; else v_separated_children = 2; } }
        //public bool b_v_children_at_risk { get { return v_children_at_risk == 1; } set { if (value) v_children_at_risk = 1; else v_children_at_risk = 2; } }
        //public bool b_v_minor_hh { get { return v_minor_hh == 1; } set { if (value) v_minor_hh = 1; else v_minor_hh = 2; } }
        //public bool b_v_female_hh { get { return v_female_hh == 1; } set { if (value) v_female_hh = 1; else v_female_hh = 2; } }
        //public bool b_v_women_at_risk { get { return v_women_at_risk == 1; } set { if (value) v_women_at_risk = 1; else v_women_at_risk = 2; } }
        //public bool b_v_older_at_risk { get { return v_older_at_risk == 1; } set { if (value) v_older_at_risk = 1; else v_older_at_risk = 2; } }
        //public bool b_v_single_parent { get { return v_single_parent == 1; } set { if (value) v_single_parent = 1; else v_single_parent = 2; } }
        //public bool b_v_physical_disability { get { return v_physical_disability == 1; } set { if (value) v_physical_disability = 1; else v_physical_disability = 2; } }
        //public bool b_v_mental_disability { get { return v_mental_disability == 1; } set { if (value) v_mental_disability = 1; else v_mental_disability = 2; } }
        //public bool b_v_serious_med_condition { get { return v_serious_med_condition == 1; } set { if (value) v_serious_med_condition = 1; else v_serious_med_condition = 2; } }
        //public bool b_v_missing_relatives { get { return v_missing_relatives == 1; } set { if (value) v_missing_relatives = 1; else v_missing_relatives = 2; } }
        //public bool b_v_surviror_at_risk_of_viol { get { return v_surviror_at_risk_of_viol == 1; } set { if (value) v_surviror_at_risk_of_viol = 1; else v_surviror_at_risk_of_viol = 2; } }
        //public bool b_v_profile_based_risk { get { return v_profile_based_risk == 1; } set { if (value) v_profile_based_risk = 1; else v_profile_based_risk = 2; } }
        //public bool b_v_other { get { return v_other == 1; } set { if (value) v_other = 1; else v_other = 2; } }


        //public bool b_v_pregnant_women { get { return v_pregnant_women == 1; } set { if (value) v_pregnant_women = 1; else v_pregnant_women = 2; } }
        //public bool b_v_breastfeeding_mother { get { return v_breastfeeding_mother == 1; } set { if (value) v_breastfeeding_mother = 1; else v_breastfeeding_mother = 2; } }
        //public bool b_v_male_hh { get { return v_male_hh == 1; } set { if (value) v_male_hh = 1; else v_male_hh = 2; } }



        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual iom_group_assessment_1 iom_group_assessment_1
        {
            get { return _iom_group_assessment_1; }
            set
            {
                if (!ReferenceEquals(_iom_group_assessment_1, value))
                {
                    var previousValue = _iom_group_assessment_1;
                    _iom_group_assessment_1 = value;
                    Fixupiom_group_assessment_1(previousValue);
                }
            }
        }
        private iom_group_assessment_1 _iom_group_assessment_1;
        
    
        [DataMember]
        public virtual lkp_ChildProIncident lkp_ChildProIncident
        {
            get { return _lkp_ChildProIncident; }
            set
            {
                if (!ReferenceEquals(_lkp_ChildProIncident, value))
                {
                    var previousValue = _lkp_ChildProIncident;
                    _lkp_ChildProIncident = value;
                    Fixuplkp_ChildProIncident(previousValue);
                }
            }
        }
        private lkp_ChildProIncident _lkp_ChildProIncident;
        
    
        [DataMember]
        public virtual lkp_GBV lkp_GBV
        {
            get { return _lkp_GBV; }
            set
            {
                if (!ReferenceEquals(_lkp_GBV, value))
                {
                    var previousValue = _lkp_GBV;
                    _lkp_GBV = value;
                    Fixuplkp_GBV(previousValue);
                }
            }
        }
        private lkp_GBV _lkp_GBV;
        
    
        [DataMember]
        public virtual lkp_HealthProblem lkp_HealthProblem
        {
            get { return _lkp_HealthProblem; }
            set
            {
                if (!ReferenceEquals(_lkp_HealthProblem, value))
                {
                    var previousValue = _lkp_HealthProblem;
                    _lkp_HealthProblem = value;
                    Fixuplkp_HealthProblem(previousValue);
                }
            }
        }
        private lkp_HealthProblem _lkp_HealthProblem;
        
    
        [DataMember]
        public virtual lkp_Incident lkp_Incident
        {
            get { return _lkp_Incident; }
            set
            {
                if (!ReferenceEquals(_lkp_Incident, value))
                {
                    var previousValue = _lkp_Incident;
                    _lkp_Incident = value;
                    Fixuplkp_Incident(previousValue);
                }
            }
        }
        private lkp_Incident _lkp_Incident;
        
    
        [DataMember]
        public virtual lkp_Intention lkp_Intention
        {
            get { return _lkp_Intention; }
            set
            {
                if (!ReferenceEquals(_lkp_Intention, value))
                {
                    var previousValue = _lkp_Intention;
                    _lkp_Intention = value;
                    Fixuplkp_Intention(previousValue);
                }
            }
        }
        private lkp_Intention _lkp_Intention;
        
    
        [DataMember]
        public virtual lkp_Lga lkp_Lga
        {
            get { return _lkp_Lga; }
            set
            {
                if (!ReferenceEquals(_lkp_Lga, value))
                {
                    var previousValue = _lkp_Lga;
                    _lkp_Lga = value;
                    Fixuplkp_Lga(previousValue);
                }
            }
        }
        private lkp_Lga _lkp_Lga;
        
    
        [DataMember]
        public virtual lkp_NeededNFI lkp_NeededNFI
        {
            get { return _lkp_NeededNFI; }
            set
            {
                if (!ReferenceEquals(_lkp_NeededNFI, value))
                {
                    var previousValue = _lkp_NeededNFI;
                    _lkp_NeededNFI = value;
                    Fixuplkp_NeededNFI(previousValue);
                }
            }
        }
        private lkp_NeededNFI _lkp_NeededNFI;
        
    
        [DataMember]
        public virtual lkp_Opportunity lkp_Opportunity
        {
            get { return _lkp_Opportunity; }
            set
            {
                if (!ReferenceEquals(_lkp_Opportunity, value))
                {
                    var previousValue = _lkp_Opportunity;
                    _lkp_Opportunity = value;
                    Fixuplkp_Opportunity(previousValue);
                }
            }
        }
        private lkp_Opportunity _lkp_Opportunity;
        
    
        [DataMember]
        public virtual lkp_Relationship_Type lkp_Relationship_Type
        {
            get { return _lkp_Relationship_Type; }
            set
            {
                if (!ReferenceEquals(_lkp_Relationship_Type, value))
                {
                    var previousValue = _lkp_Relationship_Type;
                    _lkp_Relationship_Type = value;
                    Fixuplkp_Relationship_Type(previousValue);
                }
            }
        }
        private lkp_Relationship_Type _lkp_Relationship_Type;
        
    
        [DataMember]
        public virtual lkp_TravelLocation lkp_TravelLocation
        {
            get { return _lkp_TravelLocation; }
            set
            {
                if (!ReferenceEquals(_lkp_TravelLocation, value))
                {
                    var previousValue = _lkp_TravelLocation;
                    _lkp_TravelLocation = value;
                    Fixuplkp_TravelLocation(previousValue);
                }
            }
        }
        private lkp_TravelLocation _lkp_TravelLocation;
        
    
        [DataMember]
        public virtual lkp_Ward lkp_Ward
        {
            get { return _lkp_Ward; }
            set
            {
                if (!ReferenceEquals(_lkp_Ward, value))
                {
                    var previousValue = _lkp_Ward;
                    _lkp_Ward = value;
                    Fixuplkp_Ward(previousValue);
                }
            }
        }
        private lkp_Ward _lkp_Ward;
        
    
        [DataMember]
        public virtual lkp_YesNo lkp_YesNo
        {
            get { return _lkp_YesNo; }
            set
            {
                if (!ReferenceEquals(_lkp_YesNo, value))
                {
                    var previousValue = _lkp_YesNo;
                    _lkp_YesNo = value;
                    Fixuplkp_YesNo(previousValue);
                }
            }
        }
        private lkp_YesNo _lkp_YesNo;
        
    
        [DataMember]
        public virtual lkp_YesNo lkp_YesNo1
        {
            get { return _lkp_YesNo1; }
            set
            {
                if (!ReferenceEquals(_lkp_YesNo1, value))
                {
                    var previousValue = _lkp_YesNo1;
                    _lkp_YesNo1 = value;
                    Fixuplkp_YesNo1(previousValue);
                }
            }
        }
        private lkp_YesNo _lkp_YesNo1;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixupiom_group_assessment_1(iom_group_assessment_1 previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.iom_group_assessment_2, this))
            {
                previousValue.iom_group_assessment_2 = null;
            }
    
            if (iom_group_assessment_1 != null)
            {
                iom_group_assessment_1.iom_group_assessment_2 = this;
                if (id != iom_group_assessment_1.id)
                {
                    id = iom_group_assessment_1.id;
                }
            }
        }
    
        private void Fixuplkp_ChildProIncident(lkp_ChildProIncident previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_2.Contains(this))
            {
                previousValue.iom_group_assessment_2.Remove(this);
            }
    
            if (lkp_ChildProIncident != null)
            {
                if (!lkp_ChildProIncident.iom_group_assessment_2.Contains(this))
                {
                    lkp_ChildProIncident.iom_group_assessment_2.Add(this);
                }
                if (protect_common_child_p_incident != lkp_ChildProIncident.id)
                {
                    protect_common_child_p_incident = lkp_ChildProIncident.id;
                }
            }
            else if (!_settingFK)
            {
                protect_common_child_p_incident = null;
            }
        }
    
        private void Fixuplkp_GBV(lkp_GBV previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_2.Contains(this))
            {
                previousValue.iom_group_assessment_2.Remove(this);
            }
    
            if (lkp_GBV != null)
            {
                if (!lkp_GBV.iom_group_assessment_2.Contains(this))
                {
                    lkp_GBV.iom_group_assessment_2.Add(this);
                }
                if (protect_common_GBV != lkp_GBV.id)
                {
                    protect_common_GBV = lkp_GBV.id;
                }
            }
            else if (!_settingFK)
            {
                protect_common_GBV = null;
            }
        }
    
        private void Fixuplkp_HealthProblem(lkp_HealthProblem previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_2.Contains(this))
            {
                previousValue.iom_group_assessment_2.Remove(this);
            }
    
            if (lkp_HealthProblem != null)
            {
                if (!lkp_HealthProblem.iom_group_assessment_2.Contains(this))
                {
                    lkp_HealthProblem.iom_group_assessment_2.Add(this);
                }
                if (health_most_prevalent != lkp_HealthProblem.id)
                {
                    health_most_prevalent = lkp_HealthProblem.id;
                }
            }
            else if (!_settingFK)
            {
                health_most_prevalent = null;
            }
        }
    
        private void Fixuplkp_Incident(lkp_Incident previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_2.Contains(this))
            {
                previousValue.iom_group_assessment_2.Remove(this);
            }
    
            if (lkp_Incident != null)
            {
                if (!lkp_Incident.iom_group_assessment_2.Contains(this))
                {
                    lkp_Incident.iom_group_assessment_2.Add(this);
                }
                if (protect_common_incident != lkp_Incident.id)
                {
                    protect_common_incident = lkp_Incident.id;
                }
            }
            else if (!_settingFK)
            {
                protect_common_incident = null;
            }
        }
    
        private void Fixuplkp_Intention(lkp_Intention previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_2.Contains(this))
            {
                previousValue.iom_group_assessment_2.Remove(this);
            }
    
            if (lkp_Intention != null)
            {
                if (!lkp_Intention.iom_group_assessment_2.Contains(this))
                {
                    lkp_Intention.iom_group_assessment_2.Add(this);
                }
                if (intention_of_majority != lkp_Intention.id)
                {
                    intention_of_majority = lkp_Intention.id;
                }
            }
            else if (!_settingFK)
            {
                intention_of_majority = null;
            }
        }
    
        private void Fixuplkp_Lga(lkp_Lga previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_2.Contains(this))
            {
                previousValue.iom_group_assessment_2.Remove(this);
            }
    
            if (lkp_Lga != null)
            {
                if (!lkp_Lga.iom_group_assessment_2.Contains(this))
                {
                    lkp_Lga.iom_group_assessment_2.Add(this);
                }
                if (if_yes_lga_maj != lkp_Lga.lga_code)
                {
                    if_yes_lga_maj = lkp_Lga.lga_code;
                }
            }
            else if (!_settingFK)
            {
                if_yes_lga_maj = null;
            }
        }
    
        private void Fixuplkp_NeededNFI(lkp_NeededNFI previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_2.Contains(this))
            {
                previousValue.iom_group_assessment_2.Remove(this);
            }
    
            if (lkp_NeededNFI != null)
            {
                if (!lkp_NeededNFI.iom_group_assessment_2.Contains(this))
                {
                    lkp_NeededNFI.iom_group_assessment_2.Add(this);
                }
                if (shelter_mn_nfi != lkp_NeededNFI.id)
                {
                    shelter_mn_nfi = lkp_NeededNFI.id;
                }
            }
            else if (!_settingFK)
            {
                shelter_mn_nfi = null;
            }
        }
    
        private void Fixuplkp_Opportunity(lkp_Opportunity previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_2.Contains(this))
            {
                previousValue.iom_group_assessment_2.Remove(this);
            }
    
            if (lkp_Opportunity != null)
            {
                if (!lkp_Opportunity.iom_group_assessment_2.Contains(this))
                {
                    lkp_Opportunity.iom_group_assessment_2.Add(this);
                }
                if (protect_travel_oic_ifYes_what != lkp_Opportunity.id)
                {
                    protect_travel_oic_ifYes_what = lkp_Opportunity.id;
                }
            }
            else if (!_settingFK)
            {
                protect_travel_oic_ifYes_what = null;
            }
        }
    
        private void Fixuplkp_Relationship_Type(lkp_Relationship_Type previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_2.Contains(this))
            {
                previousValue.iom_group_assessment_2.Remove(this);
            }
    
            if (lkp_Relationship_Type != null)
            {
                if (!lkp_Relationship_Type.iom_group_assessment_2.Contains(this))
                {
                    lkp_Relationship_Type.iom_group_assessment_2.Add(this);
                }
                if (sec_relationship_idp_comm != lkp_Relationship_Type.id)
                {
                    sec_relationship_idp_comm = lkp_Relationship_Type.id;
                }
            }
            else if (!_settingFK)
            {
                sec_relationship_idp_comm = null;
            }
        }
    
        private void Fixuplkp_TravelLocation(lkp_TravelLocation previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_2.Contains(this))
            {
                previousValue.iom_group_assessment_2.Remove(this);
            }
    
            if (lkp_TravelLocation != null)
            {
                if (!lkp_TravelLocation.iom_group_assessment_2.Contains(this))
                {
                    lkp_TravelLocation.iom_group_assessment_2.Add(this);
                }
                if (protect_travel_oic_ifYes_where != lkp_TravelLocation.id)
                {
                    protect_travel_oic_ifYes_where = lkp_TravelLocation.id;
                }
            }
            else if (!_settingFK)
            {
                protect_travel_oic_ifYes_where = null;
            }
        }
    
        private void Fixuplkp_Ward(lkp_Ward previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_2.Contains(this))
            {
                previousValue.iom_group_assessment_2.Remove(this);
            }
    
            if (lkp_Ward != null)
            {
                if (!lkp_Ward.iom_group_assessment_2.Contains(this))
                {
                    lkp_Ward.iom_group_assessment_2.Add(this);
                }
                if (if_yes_ward_maj != lkp_Ward.ward_code)
                {
                    if_yes_ward_maj = lkp_Ward.ward_code;
                }
            }
            else if (!_settingFK)
            {
                if_yes_ward_maj = null;
            }
        }
    
        private void Fixuplkp_YesNo(lkp_YesNo previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_2.Contains(this))
            {
                previousValue.iom_group_assessment_2.Remove(this);
            }
    
            if (lkp_YesNo != null)
            {
                if (!lkp_YesNo.iom_group_assessment_2.Contains(this))
                {
                    lkp_YesNo.iom_group_assessment_2.Add(this);
                }
                if (protect_people_feel_safe_YesNo != lkp_YesNo.id)
                {
                    protect_people_feel_safe_YesNo = lkp_YesNo.id;
                }
            }
            else if (!_settingFK)
            {
                protect_people_feel_safe_YesNo = null;
            }
        }
    
        private void Fixuplkp_YesNo1(lkp_YesNo previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_21.Contains(this))
            {
                previousValue.iom_group_assessment_21.Remove(this);
            }
    
            if (lkp_YesNo1 != null)
            {
                if (!lkp_YesNo1.iom_group_assessment_21.Contains(this))
                {
                    lkp_YesNo1.iom_group_assessment_21.Add(this);
                }
                if (protect_travel_oic_YesNo != lkp_YesNo1.id)
                {
                    protect_travel_oic_YesNo = lkp_YesNo1.id;
                }
            }
            else if (!_settingFK)
            {
                protect_travel_oic_YesNo = null;
            }
        }

        #endregion
    }
}
