//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DTM_Nigeria.Models
{
    public partial class iom_ward_profile
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get { return _id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_id != value)
                    {
                        if (iom_presence_wards != null && iom_presence_wards.id != value)
                        {
                            iom_presence_wards = null;
                        }
                        _id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _id;
    
        public virtual string date
        {
            get;
            set;
        }
    
        public virtual int researcher_id
        {
            get { return _researcher_id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_researcher_id != value)
                    {
                        if (iom_researchers != null && iom_researchers.id != value)
                        {
                            iom_researchers = null;
                        }
                        _researcher_id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _researcher_id;
    
        public virtual string settlement
        {
            get;
            set;
        }
    
        public virtual string settlement_type
        {
            get { return _settlement_type; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_settlement_type != value)
                    {
                        if (lkp_Settlement != null && lkp_Settlement.id != value)
                        {
                            lkp_Settlement = null;
                        }
                        _settlement_type = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private string _settlement_type;
    
        public virtual int displaced_hh_ind_YesNo
        {
            get;
            set;
        }
    
        public virtual Nullable<int> number_hh
        {
            get;
            set;
        }
    
        public virtual Nullable<int> number_ind
        {
            get;
            set;
        }
    
        public virtual int nr_YesNo
        {
            get;
            set;
        }
    
        public virtual string nr_location
        {
            get { return _nr_location; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_nr_location != value)
                    {
                        if (lkp_NotReturnLocation != null && lkp_NotReturnLocation.id != value)
                        {
                            lkp_NotReturnLocation = null;
                        }
                        _nr_location = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private string _nr_location;
    
        public virtual string nr_state1
        {
            get { return _nr_state1; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_nr_state1 != value)
                    {
                        if (lkp_State != null && lkp_State.state_code != value)
                        {
                            lkp_State = null;
                        }
                        _nr_state1 = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private string _nr_state1;
    
        public virtual string nr_state2
        {
            get { return _nr_state2; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_nr_state2 != value)
                    {
                        if (lkp_State1 != null && lkp_State1.state_code != value)
                        {
                            lkp_State1 = null;
                        }
                        _nr_state2 = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private string _nr_state2;
    
        public virtual Nullable<int> nr_period
        {
            get { return _nr_period; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_nr_period != value)
                    {
                        if (lkp_Period2 != null && lkp_Period2.id != value)
                        {
                            lkp_Period2 = null;
                        }
                        _nr_period = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _nr_period;
    
        public virtual int reason_insurgency_YesNo
        {
            get;
            set;
        }
    
        public virtual Nullable<int> reason_insurg_year
        {
            get { return _reason_insurg_year; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_reason_insurg_year != value)
                    {
                        if (lkp_Period21 != null && lkp_Period21.id != value)
                        {
                            lkp_Period21 = null;
                        }
                        _reason_insurg_year = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _reason_insurg_year;
    
        public virtual Nullable<int> reason_insurg_hh
        {
            get;
            set;
        }
    
        public virtual Nullable<int> reason_insurg_ind
        {
            get;
            set;
        }
    
        public virtual int reason_clash_YesNo
        {
            get;
            set;
        }
    
        public virtual Nullable<int> reason_clash_year
        {
            get { return _reason_clash_year; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_reason_clash_year != value)
                    {
                        if (lkp_Period22 != null && lkp_Period22.id != value)
                        {
                            lkp_Period22 = null;
                        }
                        _reason_clash_year = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _reason_clash_year;
    
        public virtual Nullable<int> reason_clash_hh
        {
            get;
            set;
        }
    
        public virtual Nullable<int> reason_clash_ind
        {
            get;
            set;
        }
    
        public virtual int reason_disaster_YesNo
        {
            get;
            set;
        }
    
        public virtual Nullable<int> reason_disaster_year
        {
            get { return _reason_disaster_year; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_reason_disaster_year != value)
                    {
                        if (lkp_Period23 != null && lkp_Period23.id != value)
                        {
                            lkp_Period23 = null;
                        }
                        _reason_disaster_year = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _reason_disaster_year;
    
        public virtual Nullable<int> reason_disaster_hh
        {
            get;
            set;
        }
    
        public virtual Nullable<int> reason_disaster_ind
        {
            get;
            set;
        }
    
        public virtual int reason_others_YesNo
        {
            get;
            set;
        }
    
        public virtual string reason_others_name
        {
            get;
            set;
        }
    
        public virtual Nullable<int> reason_others_year
        {
            get { return _reason_others_year; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_reason_others_year != value)
                    {
                        if (lkp_Period24 != null && lkp_Period24.id != value)
                        {
                            lkp_Period24 = null;
                        }
                        _reason_others_year = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _reason_others_year;
    
        public virtual Nullable<int> reason_others_hh
        {
            get;
            set;
        }
    
        public virtual Nullable<int> reason_others_ind
        {
            get;
            set;
        }
    
        public virtual int temporary_settlement_type_camp_YesNo
        {
            get;
            set;
        }
    
        public virtual Nullable<int> temporary_settlement_hh_camp
        {
            get;
            set;
        }
    
        public virtual Nullable<int> temporary_settlement_ind_camp
        {
            get;
            set;
        }
    
        public virtual int temporary_settlement_type_hc_YesNo
        {
            get;
            set;
        }
    
        public virtual Nullable<int> temporary_settlement_hh_hc
        {
            get;
            set;
        }
    
        public virtual Nullable<int> temporary_settlement_ind_hc
        {
            get;
            set;
        }
    
        public virtual Nullable<int> housing_shelter
        {
            get { return _housing_shelter; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_housing_shelter != value)
                    {
                        if (lkp_cmp_idp_hc != null && lkp_cmp_idp_hc.id != value)
                        {
                            lkp_cmp_idp_hc = null;
                        }
                        _housing_shelter = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _housing_shelter;
    
        public virtual Nullable<int> drinking_water
        {
            get { return _drinking_water; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_drinking_water != value)
                    {
                        if (lkp_cmp_idp_hc1 != null && lkp_cmp_idp_hc1.id != value)
                        {
                            lkp_cmp_idp_hc1 = null;
                        }
                        _drinking_water = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _drinking_water;
    
        public virtual Nullable<int> food
        {
            get { return _food; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_food != value)
                    {
                        if (lkp_cmp_idp_hc2 != null && lkp_cmp_idp_hc2.id != value)
                        {
                            lkp_cmp_idp_hc2 = null;
                        }
                        _food = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _food;
    
        public virtual Nullable<int> medical_care
        {
            get { return _medical_care; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_medical_care != value)
                    {
                        if (lkp_cmp_idp_hc3 != null && lkp_cmp_idp_hc3.id != value)
                        {
                            lkp_cmp_idp_hc3 = null;
                        }
                        _medical_care = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _medical_care;
    
        public virtual Nullable<int> access_edu
        {
            get { return _access_edu; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_access_edu != value)
                    {
                        if (lkp_cmp_idp_hc4 != null && lkp_cmp_idp_hc4.id != value)
                        {
                            lkp_cmp_idp_hc4 = null;
                        }
                        _access_edu = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _access_edu;
    
        public virtual Nullable<int> hygiene_kits
        {
            get { return _hygiene_kits; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_hygiene_kits != value)
                    {
                        if (lkp_cmp_idp_hc5 != null && lkp_cmp_idp_hc5.id != value)
                        {
                            lkp_cmp_idp_hc5 = null;
                        }
                        _hygiene_kits = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _hygiene_kits;
    
        public virtual Nullable<int> sewage_disp
        {
            get { return _sewage_disp; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_sewage_disp != value)
                    {
                        if (lkp_cmp_idp_hc6 != null && lkp_cmp_idp_hc6.id != value)
                        {
                            lkp_cmp_idp_hc6 = null;
                        }
                        _sewage_disp = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _sewage_disp;
    
        public virtual Nullable<int> hospitality_extent
        {
            get { return _hospitality_extent; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_hospitality_extent != value)
                    {
                        if (lkp_hospitality != null && lkp_hospitality.id != value)
                        {
                            lkp_hospitality = null;
                        }
                        _hospitality_extent = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _hospitality_extent;
    
        public virtual Nullable<int> diff_cause_issues
        {
            get { return _diff_cause_issues; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_diff_cause_issues != value)
                    {
                        if (lkp_YesNo != null && lkp_YesNo.id != value)
                        {
                            lkp_YesNo = null;
                        }
                        _diff_cause_issues = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _diff_cause_issues;
    
        public virtual Nullable<int> tensions_idp_hc
        {
            get { return _tensions_idp_hc; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_tensions_idp_hc != value)
                    {
                        if (lkp_tensions != null && lkp_tensions.id != value)
                        {
                            lkp_tensions = null;
                        }
                        _tensions_idp_hc = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _tensions_idp_hc;
    
        public virtual Nullable<int> collabo_idp_hc
        {
            get { return _collabo_idp_hc; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_collabo_idp_hc != value)
                    {
                        if (lkp_collabo != null && lkp_collabo.id != value)
                        {
                            lkp_collabo = null;
                        }
                        _collabo_idp_hc = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _collabo_idp_hc;
    
        public virtual Nullable<int> res_shr_idp_hc
        {
            get { return _res_shr_idp_hc; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_res_shr_idp_hc != value)
                    {
                        if (lkp_collabo1 != null && lkp_collabo1.id != value)
                        {
                            lkp_collabo1 = null;
                        }
                        _res_shr_idp_hc = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _res_shr_idp_hc;
    
        public virtual Nullable<int> stigma_toward1
        {
            get { return _stigma_toward1; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_stigma_toward1 != value)
                    {
                        if (lkp_stigma_toward != null && lkp_stigma_toward.id != value)
                        {
                            lkp_stigma_toward = null;
                        }
                        _stigma_toward1 = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _stigma_toward1;
    
        public virtual Nullable<int> stigma_toward2
        {
            get { return _stigma_toward2; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_stigma_toward2 != value)
                    {
                        if (lkp_stigma_toward1 != null && lkp_stigma_toward1.id != value)
                        {
                            lkp_stigma_toward1 = null;
                        }
                        _stigma_toward2 = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _stigma_toward2;
    
        public virtual Nullable<int> stigma_toward3
        {
            get { return _stigma_toward3; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_stigma_toward3 != value)
                    {
                        if (lkp_stigma_toward2 != null && lkp_stigma_toward2.id != value)
                        {
                            lkp_stigma_toward2 = null;
                        }
                        _stigma_toward3 = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _stigma_toward3;
    
        public virtual Nullable<int> trust_ppl1
        {
            get { return _trust_ppl1; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_trust_ppl1 != value)
                    {
                        if (lkp_trust_ppl_degree != null && lkp_trust_ppl_degree.id != value)
                        {
                            lkp_trust_ppl_degree = null;
                        }
                        _trust_ppl1 = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _trust_ppl1;
    
        public virtual Nullable<int> trust_ppl2
        {
            get { return _trust_ppl2; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_trust_ppl2 != value)
                    {
                        if (lkp_trust_ppl_degree1 != null && lkp_trust_ppl_degree1.id != value)
                        {
                            lkp_trust_ppl_degree1 = null;
                        }
                        _trust_ppl2 = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _trust_ppl2;
    
        public virtual Nullable<int> trust_ppl3
        {
            get { return _trust_ppl3; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_trust_ppl3 != value)
                    {
                        if (lkp_trust_ppl_degree2 != null && lkp_trust_ppl_degree2.id != value)
                        {
                            lkp_trust_ppl_degree2 = null;
                        }
                        _trust_ppl3 = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _trust_ppl3;
    
        public virtual Nullable<int> disp_1T_yn
        {
            get;
            set;
        }
    
        public virtual Nullable<int> disp_1T_perc
        {
            get;
            set;
        }
    
        public virtual Nullable<int> disp_2T_yn
        {
            get;
            set;
        }
    
        public virtual Nullable<int> disp_2T_perc
        {
            get;
            set;
        }
    
        public virtual string disp_2T_state
        {
            get;
            set;
        }
    
        public virtual string disp_2T_lga
        {
            get;
            set;
        }
    
        public virtual string disp_2T_ward
        {
            get;
            set;
        }
    
        public virtual Nullable<int> disp_2T_dispDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> disp_3T_yn
        {
            get;
            set;
        }
    
        public virtual Nullable<int> disp_3T_perc
        {
            get;
            set;
        }
    
        public virtual string disp_3T_state
        {
            get;
            set;
        }
    
        public virtual string disp_3T_lga
        {
            get;
            set;
        }
    
        public virtual string disp_3T_ward
        {
            get;
            set;
        }
    
        public virtual Nullable<int> disp_3T_dispDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> disp_3Tp_yn
        {
            get;
            set;
        }
    
        public virtual Nullable<int> disp_3Tp_perc
        {
            get;
            set;
        }
    
        public virtual string disp_3Tp_state
        {
            get;
            set;
        }
    
        public virtual string disp_3Tp_lga
        {
            get;
            set;
        }
    
        public virtual string disp_3Tp_ward
        {
            get;
            set;
        }
    
        public virtual Nullable<int> disp_3Tp_dispDate
        {
            get;
            set;
        }
    
        public virtual Nullable<int> idps_fromLGA_dispInWard
        {
            get;
            set;
        }
    
        public virtual Nullable<int> NbHH_dispInWard
        {
            get;
            set;
        }
    
        public virtual Nullable<int> NbIND_dispInWard
        {
            get;
            set;
        }
    
        public virtual string state_prev_disp_LargestGrp1
        {
            get;
            set;
        }
    
        public virtual string lga_prev_disp_LargestGrp1
        {
            get;
            set;
        }
    
        public virtual string date_arriv_LGA_LargestGrp1
        {
            get;
            set;
        }
    
        public virtual Nullable<int> NbHH_LargestGrp1
        {
            get;
            set;
        }
    
        public virtual Nullable<int> NbIND_LargestGrp1
        {
            get;
            set;
        }
    
        public virtual string state_prev_disp_LargestGrp2
        {
            get;
            set;
        }
    
        public virtual string lga_prev_disp_LargestGrp2
        {
            get;
            set;
        }
    
        public virtual string date_arriv_LGA_LargestGrp2
        {
            get;
            set;
        }
    
        public virtual Nullable<int> NbHH_LargestGrp2
        {
            get;
            set;
        }
    
        public virtual Nullable<int> NbIND_LargestGrp2
        {
            get;
            set;
        }
    
        public virtual Nullable<int> NbHH_makeshift
        {
            get;
            set;
        }
    
        public virtual Nullable<int> NbHH_overcrowded_houses
        {
            get;
            set;
        }
    
        public virtual Nullable<int> NbHH_damaged_houses
        {
            get;
            set;
        }
    
        public virtual Nullable<int> NbHH_living_outdoors
        {
            get;
            set;
        }
    
        public virtual Nullable<int> NbHH_need_NFI
        {
            get;
            set;
        }
    
        public virtual Nullable<int> NbHH_need_KitchenSet
        {
            get;
            set;
        }
    
        public virtual Nullable<int> NbHH_need_Full_kits
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> create_time
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> update_time
        {
            get;
            set;
        }
    
        public virtual string created_by
        {
            get;
            set;
        }
    
        public virtual string updated_by
        {
            get;
            set;
        }
    
        public virtual Nullable<int> disp_1T_dispDate
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<iom_b2f_informants> iom_b2f_informants
        {
            get
            {
                if (_iom_b2f_informants == null)
                {
                    var newCollection = new FixupCollection<iom_b2f_informants>();
                    newCollection.CollectionChanged += Fixupiom_b2f_informants;
                    _iom_b2f_informants = newCollection;
                }
                return _iom_b2f_informants;
            }
            set
            {
                if (!ReferenceEquals(_iom_b2f_informants, value))
                {
                    var previousValue = _iom_b2f_informants as FixupCollection<iom_b2f_informants>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_b2f_informants;
                    }
                    _iom_b2f_informants = value;
                    var newValue = value as FixupCollection<iom_b2f_informants>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_b2f_informants;
                    }
                }
            }
        }
        private ICollection<iom_b2f_informants> _iom_b2f_informants;
    
        public virtual ICollection<iom_b2f_organizations_assisting> iom_b2f_organizations_assisting
        {
            get
            {
                if (_iom_b2f_organizations_assisting == null)
                {
                    var newCollection = new FixupCollection<iom_b2f_organizations_assisting>();
                    newCollection.CollectionChanged += Fixupiom_b2f_organizations_assisting;
                    _iom_b2f_organizations_assisting = newCollection;
                }
                return _iom_b2f_organizations_assisting;
            }
            set
            {
                if (!ReferenceEquals(_iom_b2f_organizations_assisting, value))
                {
                    var previousValue = _iom_b2f_organizations_assisting as FixupCollection<iom_b2f_organizations_assisting>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_b2f_organizations_assisting;
                    }
                    _iom_b2f_organizations_assisting = value;
                    var newValue = value as FixupCollection<iom_b2f_organizations_assisting>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_b2f_organizations_assisting;
                    }
                }
            }
        }
        private ICollection<iom_b2f_organizations_assisting> _iom_b2f_organizations_assisting;
    
        public virtual ICollection<iom_group_assessment_1> iom_group_assessment_1
        {
            get
            {
                if (_iom_group_assessment_1 == null)
                {
                    var newCollection = new FixupCollection<iom_group_assessment_1>();
                    newCollection.CollectionChanged += Fixupiom_group_assessment_1;
                    _iom_group_assessment_1 = newCollection;
                }
                return _iom_group_assessment_1;
            }
            set
            {
                if (!ReferenceEquals(_iom_group_assessment_1, value))
                {
                    var previousValue = _iom_group_assessment_1 as FixupCollection<iom_group_assessment_1>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_group_assessment_1;
                    }
                    _iom_group_assessment_1 = value;
                    var newValue = value as FixupCollection<iom_group_assessment_1>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_group_assessment_1;
                    }
                }
            }
        }
        private ICollection<iom_group_assessment_1> _iom_group_assessment_1;
    
        public virtual iom_presence_wards iom_presence_wards
        {
            get { return _iom_presence_wards; }
            set
            {
                if (!ReferenceEquals(_iom_presence_wards, value))
                {
                    var previousValue = _iom_presence_wards;
                    _iom_presence_wards = value;
                    Fixupiom_presence_wards(previousValue);
                }
            }
        }
        private iom_presence_wards _iom_presence_wards;
    
        public virtual iom_researchers iom_researchers
        {
            get { return _iom_researchers; }
            set
            {
                if (!ReferenceEquals(_iom_researchers, value))
                {
                    var previousValue = _iom_researchers;
                    _iom_researchers = value;
                    Fixupiom_researchers(previousValue);
                }
            }
        }
        private iom_researchers _iom_researchers;
    
        public virtual ICollection<iom_ward_households_breakdown> iom_ward_households_breakdown
        {
            get
            {
                if (_iom_ward_households_breakdown == null)
                {
                    var newCollection = new FixupCollection<iom_ward_households_breakdown>();
                    newCollection.CollectionChanged += Fixupiom_ward_households_breakdown;
                    _iom_ward_households_breakdown = newCollection;
                }
                return _iom_ward_households_breakdown;
            }
            set
            {
                if (!ReferenceEquals(_iom_ward_households_breakdown, value))
                {
                    var previousValue = _iom_ward_households_breakdown as FixupCollection<iom_ward_households_breakdown>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_ward_households_breakdown;
                    }
                    _iom_ward_households_breakdown = value;
                    var newValue = value as FixupCollection<iom_ward_households_breakdown>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_ward_households_breakdown;
                    }
                }
            }
        }
        private ICollection<iom_ward_households_breakdown> _iom_ward_households_breakdown;
    
        public virtual ICollection<iom_ward_idp_arrival> iom_ward_idp_arrival
        {
            get
            {
                if (_iom_ward_idp_arrival == null)
                {
                    var newCollection = new FixupCollection<iom_ward_idp_arrival>();
                    newCollection.CollectionChanged += Fixupiom_ward_idp_arrival;
                    _iom_ward_idp_arrival = newCollection;
                }
                return _iom_ward_idp_arrival;
            }
            set
            {
                if (!ReferenceEquals(_iom_ward_idp_arrival, value))
                {
                    var previousValue = _iom_ward_idp_arrival as FixupCollection<iom_ward_idp_arrival>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_ward_idp_arrival;
                    }
                    _iom_ward_idp_arrival = value;
                    var newValue = value as FixupCollection<iom_ward_idp_arrival>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_ward_idp_arrival;
                    }
                }
            }
        }
        private ICollection<iom_ward_idp_arrival> _iom_ward_idp_arrival;
    
        public virtual ICollection<iom_ward_presence_per_location> iom_ward_presence_per_location
        {
            get
            {
                if (_iom_ward_presence_per_location == null)
                {
                    var newCollection = new FixupCollection<iom_ward_presence_per_location>();
                    newCollection.CollectionChanged += Fixupiom_ward_presence_per_location;
                    _iom_ward_presence_per_location = newCollection;
                }
                return _iom_ward_presence_per_location;
            }
            set
            {
                if (!ReferenceEquals(_iom_ward_presence_per_location, value))
                {
                    var previousValue = _iom_ward_presence_per_location as FixupCollection<iom_ward_presence_per_location>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_ward_presence_per_location;
                    }
                    _iom_ward_presence_per_location = value;
                    var newValue = value as FixupCollection<iom_ward_presence_per_location>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_ward_presence_per_location;
                    }
                }
            }
        }
        private ICollection<iom_ward_presence_per_location> _iom_ward_presence_per_location;
    
        public virtual lkp_cmp_idp_hc lkp_cmp_idp_hc
        {
            get { return _lkp_cmp_idp_hc; }
            set
            {
                if (!ReferenceEquals(_lkp_cmp_idp_hc, value))
                {
                    var previousValue = _lkp_cmp_idp_hc;
                    _lkp_cmp_idp_hc = value;
                    Fixuplkp_cmp_idp_hc(previousValue);
                }
            }
        }
        private lkp_cmp_idp_hc _lkp_cmp_idp_hc;
    
        public virtual lkp_cmp_idp_hc lkp_cmp_idp_hc1
        {
            get { return _lkp_cmp_idp_hc1; }
            set
            {
                if (!ReferenceEquals(_lkp_cmp_idp_hc1, value))
                {
                    var previousValue = _lkp_cmp_idp_hc1;
                    _lkp_cmp_idp_hc1 = value;
                    Fixuplkp_cmp_idp_hc1(previousValue);
                }
            }
        }
        private lkp_cmp_idp_hc _lkp_cmp_idp_hc1;
    
        public virtual lkp_cmp_idp_hc lkp_cmp_idp_hc2
        {
            get { return _lkp_cmp_idp_hc2; }
            set
            {
                if (!ReferenceEquals(_lkp_cmp_idp_hc2, value))
                {
                    var previousValue = _lkp_cmp_idp_hc2;
                    _lkp_cmp_idp_hc2 = value;
                    Fixuplkp_cmp_idp_hc2(previousValue);
                }
            }
        }
        private lkp_cmp_idp_hc _lkp_cmp_idp_hc2;
    
        public virtual lkp_cmp_idp_hc lkp_cmp_idp_hc3
        {
            get { return _lkp_cmp_idp_hc3; }
            set
            {
                if (!ReferenceEquals(_lkp_cmp_idp_hc3, value))
                {
                    var previousValue = _lkp_cmp_idp_hc3;
                    _lkp_cmp_idp_hc3 = value;
                    Fixuplkp_cmp_idp_hc3(previousValue);
                }
            }
        }
        private lkp_cmp_idp_hc _lkp_cmp_idp_hc3;
    
        public virtual lkp_cmp_idp_hc lkp_cmp_idp_hc4
        {
            get { return _lkp_cmp_idp_hc4; }
            set
            {
                if (!ReferenceEquals(_lkp_cmp_idp_hc4, value))
                {
                    var previousValue = _lkp_cmp_idp_hc4;
                    _lkp_cmp_idp_hc4 = value;
                    Fixuplkp_cmp_idp_hc4(previousValue);
                }
            }
        }
        private lkp_cmp_idp_hc _lkp_cmp_idp_hc4;
    
        public virtual lkp_cmp_idp_hc lkp_cmp_idp_hc5
        {
            get { return _lkp_cmp_idp_hc5; }
            set
            {
                if (!ReferenceEquals(_lkp_cmp_idp_hc5, value))
                {
                    var previousValue = _lkp_cmp_idp_hc5;
                    _lkp_cmp_idp_hc5 = value;
                    Fixuplkp_cmp_idp_hc5(previousValue);
                }
            }
        }
        private lkp_cmp_idp_hc _lkp_cmp_idp_hc5;
    
        public virtual lkp_cmp_idp_hc lkp_cmp_idp_hc6
        {
            get { return _lkp_cmp_idp_hc6; }
            set
            {
                if (!ReferenceEquals(_lkp_cmp_idp_hc6, value))
                {
                    var previousValue = _lkp_cmp_idp_hc6;
                    _lkp_cmp_idp_hc6 = value;
                    Fixuplkp_cmp_idp_hc6(previousValue);
                }
            }
        }
        private lkp_cmp_idp_hc _lkp_cmp_idp_hc6;
    
        public virtual lkp_collabo lkp_collabo
        {
            get { return _lkp_collabo; }
            set
            {
                if (!ReferenceEquals(_lkp_collabo, value))
                {
                    var previousValue = _lkp_collabo;
                    _lkp_collabo = value;
                    Fixuplkp_collabo(previousValue);
                }
            }
        }
        private lkp_collabo _lkp_collabo;
    
        public virtual lkp_collabo lkp_collabo1
        {
            get { return _lkp_collabo1; }
            set
            {
                if (!ReferenceEquals(_lkp_collabo1, value))
                {
                    var previousValue = _lkp_collabo1;
                    _lkp_collabo1 = value;
                    Fixuplkp_collabo1(previousValue);
                }
            }
        }
        private lkp_collabo _lkp_collabo1;
    
        public virtual lkp_hospitality lkp_hospitality
        {
            get { return _lkp_hospitality; }
            set
            {
                if (!ReferenceEquals(_lkp_hospitality, value))
                {
                    var previousValue = _lkp_hospitality;
                    _lkp_hospitality = value;
                    Fixuplkp_hospitality(previousValue);
                }
            }
        }
        private lkp_hospitality _lkp_hospitality;
    
        public virtual lkp_NotReturnLocation lkp_NotReturnLocation
        {
            get { return _lkp_NotReturnLocation; }
            set
            {
                if (!ReferenceEquals(_lkp_NotReturnLocation, value))
                {
                    var previousValue = _lkp_NotReturnLocation;
                    _lkp_NotReturnLocation = value;
                    Fixuplkp_NotReturnLocation(previousValue);
                }
            }
        }
        private lkp_NotReturnLocation _lkp_NotReturnLocation;
    
        public virtual lkp_Period2 lkp_Period2
        {
            get { return _lkp_Period2; }
            set
            {
                if (!ReferenceEquals(_lkp_Period2, value))
                {
                    var previousValue = _lkp_Period2;
                    _lkp_Period2 = value;
                    Fixuplkp_Period2(previousValue);
                }
            }
        }
        private lkp_Period2 _lkp_Period2;
    
        public virtual lkp_Period2 lkp_Period21
        {
            get { return _lkp_Period21; }
            set
            {
                if (!ReferenceEquals(_lkp_Period21, value))
                {
                    var previousValue = _lkp_Period21;
                    _lkp_Period21 = value;
                    Fixuplkp_Period21(previousValue);
                }
            }
        }
        private lkp_Period2 _lkp_Period21;
    
        public virtual lkp_Period2 lkp_Period22
        {
            get { return _lkp_Period22; }
            set
            {
                if (!ReferenceEquals(_lkp_Period22, value))
                {
                    var previousValue = _lkp_Period22;
                    _lkp_Period22 = value;
                    Fixuplkp_Period22(previousValue);
                }
            }
        }
        private lkp_Period2 _lkp_Period22;
    
        public virtual lkp_Period2 lkp_Period23
        {
            get { return _lkp_Period23; }
            set
            {
                if (!ReferenceEquals(_lkp_Period23, value))
                {
                    var previousValue = _lkp_Period23;
                    _lkp_Period23 = value;
                    Fixuplkp_Period23(previousValue);
                }
            }
        }
        private lkp_Period2 _lkp_Period23;
    
        public virtual lkp_Period2 lkp_Period24
        {
            get { return _lkp_Period24; }
            set
            {
                if (!ReferenceEquals(_lkp_Period24, value))
                {
                    var previousValue = _lkp_Period24;
                    _lkp_Period24 = value;
                    Fixuplkp_Period24(previousValue);
                }
            }
        }
        private lkp_Period2 _lkp_Period24;
    
        public virtual lkp_Settlement lkp_Settlement
        {
            get { return _lkp_Settlement; }
            set
            {
                if (!ReferenceEquals(_lkp_Settlement, value))
                {
                    var previousValue = _lkp_Settlement;
                    _lkp_Settlement = value;
                    Fixuplkp_Settlement(previousValue);
                }
            }
        }
        private lkp_Settlement _lkp_Settlement;
    
        public virtual lkp_State lkp_State
        {
            get { return _lkp_State; }
            set
            {
                if (!ReferenceEquals(_lkp_State, value))
                {
                    var previousValue = _lkp_State;
                    _lkp_State = value;
                    Fixuplkp_State(previousValue);
                }
            }
        }
        private lkp_State _lkp_State;
    
        public virtual lkp_State lkp_State1
        {
            get { return _lkp_State1; }
            set
            {
                if (!ReferenceEquals(_lkp_State1, value))
                {
                    var previousValue = _lkp_State1;
                    _lkp_State1 = value;
                    Fixuplkp_State1(previousValue);
                }
            }
        }
        private lkp_State _lkp_State1;
    
        public virtual lkp_stigma_toward lkp_stigma_toward
        {
            get { return _lkp_stigma_toward; }
            set
            {
                if (!ReferenceEquals(_lkp_stigma_toward, value))
                {
                    var previousValue = _lkp_stigma_toward;
                    _lkp_stigma_toward = value;
                    Fixuplkp_stigma_toward(previousValue);
                }
            }
        }
        private lkp_stigma_toward _lkp_stigma_toward;
    
        public virtual lkp_stigma_toward lkp_stigma_toward1
        {
            get { return _lkp_stigma_toward1; }
            set
            {
                if (!ReferenceEquals(_lkp_stigma_toward1, value))
                {
                    var previousValue = _lkp_stigma_toward1;
                    _lkp_stigma_toward1 = value;
                    Fixuplkp_stigma_toward1(previousValue);
                }
            }
        }
        private lkp_stigma_toward _lkp_stigma_toward1;
    
        public virtual lkp_stigma_toward lkp_stigma_toward2
        {
            get { return _lkp_stigma_toward2; }
            set
            {
                if (!ReferenceEquals(_lkp_stigma_toward2, value))
                {
                    var previousValue = _lkp_stigma_toward2;
                    _lkp_stigma_toward2 = value;
                    Fixuplkp_stigma_toward2(previousValue);
                }
            }
        }
        private lkp_stigma_toward _lkp_stigma_toward2;
    
        public virtual lkp_tensions lkp_tensions
        {
            get { return _lkp_tensions; }
            set
            {
                if (!ReferenceEquals(_lkp_tensions, value))
                {
                    var previousValue = _lkp_tensions;
                    _lkp_tensions = value;
                    Fixuplkp_tensions(previousValue);
                }
            }
        }
        private lkp_tensions _lkp_tensions;
    
        public virtual lkp_trust_ppl_degree lkp_trust_ppl_degree
        {
            get { return _lkp_trust_ppl_degree; }
            set
            {
                if (!ReferenceEquals(_lkp_trust_ppl_degree, value))
                {
                    var previousValue = _lkp_trust_ppl_degree;
                    _lkp_trust_ppl_degree = value;
                    Fixuplkp_trust_ppl_degree(previousValue);
                }
            }
        }
        private lkp_trust_ppl_degree _lkp_trust_ppl_degree;
    
        public virtual lkp_trust_ppl_degree lkp_trust_ppl_degree1
        {
            get { return _lkp_trust_ppl_degree1; }
            set
            {
                if (!ReferenceEquals(_lkp_trust_ppl_degree1, value))
                {
                    var previousValue = _lkp_trust_ppl_degree1;
                    _lkp_trust_ppl_degree1 = value;
                    Fixuplkp_trust_ppl_degree1(previousValue);
                }
            }
        }
        private lkp_trust_ppl_degree _lkp_trust_ppl_degree1;
    
        public virtual lkp_trust_ppl_degree lkp_trust_ppl_degree2
        {
            get { return _lkp_trust_ppl_degree2; }
            set
            {
                if (!ReferenceEquals(_lkp_trust_ppl_degree2, value))
                {
                    var previousValue = _lkp_trust_ppl_degree2;
                    _lkp_trust_ppl_degree2 = value;
                    Fixuplkp_trust_ppl_degree2(previousValue);
                }
            }
        }
        private lkp_trust_ppl_degree _lkp_trust_ppl_degree2;
    
        public virtual lkp_YesNo lkp_YesNo
        {
            get { return _lkp_YesNo; }
            set
            {
                if (!ReferenceEquals(_lkp_YesNo, value))
                {
                    var previousValue = _lkp_YesNo;
                    _lkp_YesNo = value;
                    Fixuplkp_YesNo(previousValue);
                }
            }
        }
        private lkp_YesNo _lkp_YesNo;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixupiom_presence_wards(iom_presence_wards previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.iom_ward_profile, this))
            {
                previousValue.iom_ward_profile = null;
            }
    
            if (iom_presence_wards != null)
            {
                iom_presence_wards.iom_ward_profile = this;
                if (id != iom_presence_wards.id)
                {
                    id = iom_presence_wards.id;
                }
            }
        }
    
        private void Fixupiom_researchers(iom_researchers previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile.Contains(this))
            {
                previousValue.iom_ward_profile.Remove(this);
            }
    
            if (iom_researchers != null)
            {
                if (!iom_researchers.iom_ward_profile.Contains(this))
                {
                    iom_researchers.iom_ward_profile.Add(this);
                }
                if (researcher_id != iom_researchers.id)
                {
                    researcher_id = iom_researchers.id;
                }
            }
        }
    
        private void Fixuplkp_cmp_idp_hc(lkp_cmp_idp_hc previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile.Contains(this))
            {
                previousValue.iom_ward_profile.Remove(this);
            }
    
            if (lkp_cmp_idp_hc != null)
            {
                if (!lkp_cmp_idp_hc.iom_ward_profile.Contains(this))
                {
                    lkp_cmp_idp_hc.iom_ward_profile.Add(this);
                }
                if (housing_shelter != lkp_cmp_idp_hc.id)
                {
                    housing_shelter = lkp_cmp_idp_hc.id;
                }
            }
            else if (!_settingFK)
            {
                housing_shelter = null;
            }
        }
    
        private void Fixuplkp_cmp_idp_hc1(lkp_cmp_idp_hc previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile1.Contains(this))
            {
                previousValue.iom_ward_profile1.Remove(this);
            }
    
            if (lkp_cmp_idp_hc1 != null)
            {
                if (!lkp_cmp_idp_hc1.iom_ward_profile1.Contains(this))
                {
                    lkp_cmp_idp_hc1.iom_ward_profile1.Add(this);
                }
                if (drinking_water != lkp_cmp_idp_hc1.id)
                {
                    drinking_water = lkp_cmp_idp_hc1.id;
                }
            }
            else if (!_settingFK)
            {
                drinking_water = null;
            }
        }
    
        private void Fixuplkp_cmp_idp_hc2(lkp_cmp_idp_hc previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile2.Contains(this))
            {
                previousValue.iom_ward_profile2.Remove(this);
            }
    
            if (lkp_cmp_idp_hc2 != null)
            {
                if (!lkp_cmp_idp_hc2.iom_ward_profile2.Contains(this))
                {
                    lkp_cmp_idp_hc2.iom_ward_profile2.Add(this);
                }
                if (food != lkp_cmp_idp_hc2.id)
                {
                    food = lkp_cmp_idp_hc2.id;
                }
            }
            else if (!_settingFK)
            {
                food = null;
            }
        }
    
        private void Fixuplkp_cmp_idp_hc3(lkp_cmp_idp_hc previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile3.Contains(this))
            {
                previousValue.iom_ward_profile3.Remove(this);
            }
    
            if (lkp_cmp_idp_hc3 != null)
            {
                if (!lkp_cmp_idp_hc3.iom_ward_profile3.Contains(this))
                {
                    lkp_cmp_idp_hc3.iom_ward_profile3.Add(this);
                }
                if (medical_care != lkp_cmp_idp_hc3.id)
                {
                    medical_care = lkp_cmp_idp_hc3.id;
                }
            }
            else if (!_settingFK)
            {
                medical_care = null;
            }
        }
    
        private void Fixuplkp_cmp_idp_hc4(lkp_cmp_idp_hc previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile4.Contains(this))
            {
                previousValue.iom_ward_profile4.Remove(this);
            }
    
            if (lkp_cmp_idp_hc4 != null)
            {
                if (!lkp_cmp_idp_hc4.iom_ward_profile4.Contains(this))
                {
                    lkp_cmp_idp_hc4.iom_ward_profile4.Add(this);
                }
                if (access_edu != lkp_cmp_idp_hc4.id)
                {
                    access_edu = lkp_cmp_idp_hc4.id;
                }
            }
            else if (!_settingFK)
            {
                access_edu = null;
            }
        }
    
        private void Fixuplkp_cmp_idp_hc5(lkp_cmp_idp_hc previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile5.Contains(this))
            {
                previousValue.iom_ward_profile5.Remove(this);
            }
    
            if (lkp_cmp_idp_hc5 != null)
            {
                if (!lkp_cmp_idp_hc5.iom_ward_profile5.Contains(this))
                {
                    lkp_cmp_idp_hc5.iom_ward_profile5.Add(this);
                }
                if (hygiene_kits != lkp_cmp_idp_hc5.id)
                {
                    hygiene_kits = lkp_cmp_idp_hc5.id;
                }
            }
            else if (!_settingFK)
            {
                hygiene_kits = null;
            }
        }
    
        private void Fixuplkp_cmp_idp_hc6(lkp_cmp_idp_hc previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile6.Contains(this))
            {
                previousValue.iom_ward_profile6.Remove(this);
            }
    
            if (lkp_cmp_idp_hc6 != null)
            {
                if (!lkp_cmp_idp_hc6.iom_ward_profile6.Contains(this))
                {
                    lkp_cmp_idp_hc6.iom_ward_profile6.Add(this);
                }
                if (sewage_disp != lkp_cmp_idp_hc6.id)
                {
                    sewage_disp = lkp_cmp_idp_hc6.id;
                }
            }
            else if (!_settingFK)
            {
                sewage_disp = null;
            }
        }
    
        private void Fixuplkp_collabo(lkp_collabo previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile.Contains(this))
            {
                previousValue.iom_ward_profile.Remove(this);
            }
    
            if (lkp_collabo != null)
            {
                if (!lkp_collabo.iom_ward_profile.Contains(this))
                {
                    lkp_collabo.iom_ward_profile.Add(this);
                }
                if (collabo_idp_hc != lkp_collabo.id)
                {
                    collabo_idp_hc = lkp_collabo.id;
                }
            }
            else if (!_settingFK)
            {
                collabo_idp_hc = null;
            }
        }
    
        private void Fixuplkp_collabo1(lkp_collabo previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile1.Contains(this))
            {
                previousValue.iom_ward_profile1.Remove(this);
            }
    
            if (lkp_collabo1 != null)
            {
                if (!lkp_collabo1.iom_ward_profile1.Contains(this))
                {
                    lkp_collabo1.iom_ward_profile1.Add(this);
                }
                if (res_shr_idp_hc != lkp_collabo1.id)
                {
                    res_shr_idp_hc = lkp_collabo1.id;
                }
            }
            else if (!_settingFK)
            {
                res_shr_idp_hc = null;
            }
        }
    
        private void Fixuplkp_hospitality(lkp_hospitality previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile.Contains(this))
            {
                previousValue.iom_ward_profile.Remove(this);
            }
    
            if (lkp_hospitality != null)
            {
                if (!lkp_hospitality.iom_ward_profile.Contains(this))
                {
                    lkp_hospitality.iom_ward_profile.Add(this);
                }
                if (hospitality_extent != lkp_hospitality.id)
                {
                    hospitality_extent = lkp_hospitality.id;
                }
            }
            else if (!_settingFK)
            {
                hospitality_extent = null;
            }
        }
    
        private void Fixuplkp_NotReturnLocation(lkp_NotReturnLocation previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile.Contains(this))
            {
                previousValue.iom_ward_profile.Remove(this);
            }
    
            if (lkp_NotReturnLocation != null)
            {
                if (!lkp_NotReturnLocation.iom_ward_profile.Contains(this))
                {
                    lkp_NotReturnLocation.iom_ward_profile.Add(this);
                }
                if (nr_location != lkp_NotReturnLocation.id)
                {
                    nr_location = lkp_NotReturnLocation.id;
                }
            }
            else if (!_settingFK)
            {
                nr_location = null;
            }
        }
    
        private void Fixuplkp_Period2(lkp_Period2 previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile.Contains(this))
            {
                previousValue.iom_ward_profile.Remove(this);
            }
    
            if (lkp_Period2 != null)
            {
                if (!lkp_Period2.iom_ward_profile.Contains(this))
                {
                    lkp_Period2.iom_ward_profile.Add(this);
                }
                if (nr_period != lkp_Period2.id)
                {
                    nr_period = lkp_Period2.id;
                }
            }
            else if (!_settingFK)
            {
                nr_period = null;
            }
        }
    
        private void Fixuplkp_Period21(lkp_Period2 previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile1.Contains(this))
            {
                previousValue.iom_ward_profile1.Remove(this);
            }
    
            if (lkp_Period21 != null)
            {
                if (!lkp_Period21.iom_ward_profile1.Contains(this))
                {
                    lkp_Period21.iom_ward_profile1.Add(this);
                }
                if (reason_insurg_year != lkp_Period21.id)
                {
                    reason_insurg_year = lkp_Period21.id;
                }
            }
            else if (!_settingFK)
            {
                reason_insurg_year = null;
            }
        }
    
        private void Fixuplkp_Period22(lkp_Period2 previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile2.Contains(this))
            {
                previousValue.iom_ward_profile2.Remove(this);
            }
    
            if (lkp_Period22 != null)
            {
                if (!lkp_Period22.iom_ward_profile2.Contains(this))
                {
                    lkp_Period22.iom_ward_profile2.Add(this);
                }
                if (reason_clash_year != lkp_Period22.id)
                {
                    reason_clash_year = lkp_Period22.id;
                }
            }
            else if (!_settingFK)
            {
                reason_clash_year = null;
            }
        }
    
        private void Fixuplkp_Period23(lkp_Period2 previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile3.Contains(this))
            {
                previousValue.iom_ward_profile3.Remove(this);
            }
    
            if (lkp_Period23 != null)
            {
                if (!lkp_Period23.iom_ward_profile3.Contains(this))
                {
                    lkp_Period23.iom_ward_profile3.Add(this);
                }
                if (reason_disaster_year != lkp_Period23.id)
                {
                    reason_disaster_year = lkp_Period23.id;
                }
            }
            else if (!_settingFK)
            {
                reason_disaster_year = null;
            }
        }
    
        private void Fixuplkp_Period24(lkp_Period2 previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile4.Contains(this))
            {
                previousValue.iom_ward_profile4.Remove(this);
            }
    
            if (lkp_Period24 != null)
            {
                if (!lkp_Period24.iom_ward_profile4.Contains(this))
                {
                    lkp_Period24.iom_ward_profile4.Add(this);
                }
                if (reason_others_year != lkp_Period24.id)
                {
                    reason_others_year = lkp_Period24.id;
                }
            }
            else if (!_settingFK)
            {
                reason_others_year = null;
            }
        }
    
        private void Fixuplkp_Settlement(lkp_Settlement previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile.Contains(this))
            {
                previousValue.iom_ward_profile.Remove(this);
            }
    
            if (lkp_Settlement != null)
            {
                if (!lkp_Settlement.iom_ward_profile.Contains(this))
                {
                    lkp_Settlement.iom_ward_profile.Add(this);
                }
                if (settlement_type != lkp_Settlement.id)
                {
                    settlement_type = lkp_Settlement.id;
                }
            }
        }
    
        private void Fixuplkp_State(lkp_State previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile.Contains(this))
            {
                previousValue.iom_ward_profile.Remove(this);
            }
    
            if (lkp_State != null)
            {
                if (!lkp_State.iom_ward_profile.Contains(this))
                {
                    lkp_State.iom_ward_profile.Add(this);
                }
                if (nr_state1 != lkp_State.state_code)
                {
                    nr_state1 = lkp_State.state_code;
                }
            }
            else if (!_settingFK)
            {
                nr_state1 = null;
            }
        }
    
        private void Fixuplkp_State1(lkp_State previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile1.Contains(this))
            {
                previousValue.iom_ward_profile1.Remove(this);
            }
    
            if (lkp_State1 != null)
            {
                if (!lkp_State1.iom_ward_profile1.Contains(this))
                {
                    lkp_State1.iom_ward_profile1.Add(this);
                }
                if (nr_state2 != lkp_State1.state_code)
                {
                    nr_state2 = lkp_State1.state_code;
                }
            }
            else if (!_settingFK)
            {
                nr_state2 = null;
            }
        }
    
        private void Fixuplkp_stigma_toward(lkp_stigma_toward previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile.Contains(this))
            {
                previousValue.iom_ward_profile.Remove(this);
            }
    
            if (lkp_stigma_toward != null)
            {
                if (!lkp_stigma_toward.iom_ward_profile.Contains(this))
                {
                    lkp_stigma_toward.iom_ward_profile.Add(this);
                }
                if (stigma_toward1 != lkp_stigma_toward.id)
                {
                    stigma_toward1 = lkp_stigma_toward.id;
                }
            }
            else if (!_settingFK)
            {
                stigma_toward1 = null;
            }
        }
    
        private void Fixuplkp_stigma_toward1(lkp_stigma_toward previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile1.Contains(this))
            {
                previousValue.iom_ward_profile1.Remove(this);
            }
    
            if (lkp_stigma_toward1 != null)
            {
                if (!lkp_stigma_toward1.iom_ward_profile1.Contains(this))
                {
                    lkp_stigma_toward1.iom_ward_profile1.Add(this);
                }
                if (stigma_toward2 != lkp_stigma_toward1.id)
                {
                    stigma_toward2 = lkp_stigma_toward1.id;
                }
            }
            else if (!_settingFK)
            {
                stigma_toward2 = null;
            }
        }
    
        private void Fixuplkp_stigma_toward2(lkp_stigma_toward previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile2.Contains(this))
            {
                previousValue.iom_ward_profile2.Remove(this);
            }
    
            if (lkp_stigma_toward2 != null)
            {
                if (!lkp_stigma_toward2.iom_ward_profile2.Contains(this))
                {
                    lkp_stigma_toward2.iom_ward_profile2.Add(this);
                }
                if (stigma_toward3 != lkp_stigma_toward2.id)
                {
                    stigma_toward3 = lkp_stigma_toward2.id;
                }
            }
            else if (!_settingFK)
            {
                stigma_toward3 = null;
            }
        }
    
        private void Fixuplkp_tensions(lkp_tensions previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile.Contains(this))
            {
                previousValue.iom_ward_profile.Remove(this);
            }
    
            if (lkp_tensions != null)
            {
                if (!lkp_tensions.iom_ward_profile.Contains(this))
                {
                    lkp_tensions.iom_ward_profile.Add(this);
                }
                if (tensions_idp_hc != lkp_tensions.id)
                {
                    tensions_idp_hc = lkp_tensions.id;
                }
            }
            else if (!_settingFK)
            {
                tensions_idp_hc = null;
            }
        }
    
        private void Fixuplkp_trust_ppl_degree(lkp_trust_ppl_degree previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile.Contains(this))
            {
                previousValue.iom_ward_profile.Remove(this);
            }
    
            if (lkp_trust_ppl_degree != null)
            {
                if (!lkp_trust_ppl_degree.iom_ward_profile.Contains(this))
                {
                    lkp_trust_ppl_degree.iom_ward_profile.Add(this);
                }
                if (trust_ppl1 != lkp_trust_ppl_degree.id)
                {
                    trust_ppl1 = lkp_trust_ppl_degree.id;
                }
            }
            else if (!_settingFK)
            {
                trust_ppl1 = null;
            }
        }
    
        private void Fixuplkp_trust_ppl_degree1(lkp_trust_ppl_degree previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile1.Contains(this))
            {
                previousValue.iom_ward_profile1.Remove(this);
            }
    
            if (lkp_trust_ppl_degree1 != null)
            {
                if (!lkp_trust_ppl_degree1.iom_ward_profile1.Contains(this))
                {
                    lkp_trust_ppl_degree1.iom_ward_profile1.Add(this);
                }
                if (trust_ppl2 != lkp_trust_ppl_degree1.id)
                {
                    trust_ppl2 = lkp_trust_ppl_degree1.id;
                }
            }
            else if (!_settingFK)
            {
                trust_ppl2 = null;
            }
        }
    
        private void Fixuplkp_trust_ppl_degree2(lkp_trust_ppl_degree previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile2.Contains(this))
            {
                previousValue.iom_ward_profile2.Remove(this);
            }
    
            if (lkp_trust_ppl_degree2 != null)
            {
                if (!lkp_trust_ppl_degree2.iom_ward_profile2.Contains(this))
                {
                    lkp_trust_ppl_degree2.iom_ward_profile2.Add(this);
                }
                if (trust_ppl3 != lkp_trust_ppl_degree2.id)
                {
                    trust_ppl3 = lkp_trust_ppl_degree2.id;
                }
            }
            else if (!_settingFK)
            {
                trust_ppl3 = null;
            }
        }
    
        private void Fixuplkp_YesNo(lkp_YesNo previousValue)
        {
            if (previousValue != null && previousValue.iom_ward_profile.Contains(this))
            {
                previousValue.iom_ward_profile.Remove(this);
            }
    
            if (lkp_YesNo != null)
            {
                if (!lkp_YesNo.iom_ward_profile.Contains(this))
                {
                    lkp_YesNo.iom_ward_profile.Add(this);
                }
                if (diff_cause_issues != lkp_YesNo.id)
                {
                    diff_cause_issues = lkp_YesNo.id;
                }
            }
            else if (!_settingFK)
            {
                diff_cause_issues = null;
            }
        }
    
        private void Fixupiom_b2f_informants(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_b2f_informants item in e.NewItems)
                {
                    item.iom_ward_profile = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_b2f_informants item in e.OldItems)
                {
                    if (ReferenceEquals(item.iom_ward_profile, this))
                    {
                        item.iom_ward_profile = null;
                    }
                }
            }
        }
    
        private void Fixupiom_b2f_organizations_assisting(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_b2f_organizations_assisting item in e.NewItems)
                {
                    item.iom_ward_profile = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_b2f_organizations_assisting item in e.OldItems)
                {
                    if (ReferenceEquals(item.iom_ward_profile, this))
                    {
                        item.iom_ward_profile = null;
                    }
                }
            }
        }
    
        private void Fixupiom_group_assessment_1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_group_assessment_1 item in e.NewItems)
                {
                    item.iom_ward_profile = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_group_assessment_1 item in e.OldItems)
                {
                    if (ReferenceEquals(item.iom_ward_profile, this))
                    {
                        item.iom_ward_profile = null;
                    }
                }
            }
        }
    
        private void Fixupiom_ward_households_breakdown(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_ward_households_breakdown item in e.NewItems)
                {
                    item.iom_ward_profile = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_ward_households_breakdown item in e.OldItems)
                {
                    if (ReferenceEquals(item.iom_ward_profile, this))
                    {
                        item.iom_ward_profile = null;
                    }
                }
            }
        }
    
        private void Fixupiom_ward_idp_arrival(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_ward_idp_arrival item in e.NewItems)
                {
                    item.iom_ward_profile = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_ward_idp_arrival item in e.OldItems)
                {
                    if (ReferenceEquals(item.iom_ward_profile, this))
                    {
                        item.iom_ward_profile = null;
                    }
                }
            }
        }
    
        private void Fixupiom_ward_presence_per_location(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_ward_presence_per_location item in e.NewItems)
                {
                    item.iom_ward_profile = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_ward_presence_per_location item in e.OldItems)
                {
                    if (ReferenceEquals(item.iom_ward_profile, this))
                    {
                        item.iom_ward_profile = null;
                    }
                }
            }
        }

        #endregion
    }
}
