//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

namespace DTM_Nigeria.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(iom_organizations))]
    [KnownType(typeof(lkp_assistance_type))]
    [KnownType(typeof(iom_ward_profile))]
    public partial class iom_b2f_organizations_assisting
    {
        #region Primitive Properties
        [DataMember]
        public virtual int id
        {
            get;
            set;
        }
        [DataMember]
        public virtual int organization
        {
            get { return _organization; }
            set
            {
                if (_organization != value)
                {
                    if (iom_organizations != null && iom_organizations.id != value)
                    {
                        iom_organizations = null;
                    }
                    _organization = value;
                }
            }
        }
        private int _organization;
        [DataMember]
        public virtual int ward_profile_id
        {
            get { return _ward_profile_id; }
            set
            {
                if (_ward_profile_id != value)
                {
                    if (iom_ward_profile != null && iom_ward_profile.id != value)
                    {
                        iom_ward_profile = null;
                    }
                    _ward_profile_id = value;
                }
            }
        }
        private int _ward_profile_id;
        [DataMember]
        [Required(ErrorMessage = "*")]
        public virtual int assistance_type
        {
            get { return _assistance_type; }
            set
            {
                if (_assistance_type != value)
                {
                    if (lkp_assistance_type != null && lkp_assistance_type.id != value)
                    {
                        lkp_assistance_type = null;
                    }
                    _assistance_type = value;
                }
            }
        }
        private int _assistance_type;
        [DataMember]
        [Required(ErrorMessage = "*", AllowEmptyStrings = false)]
        public virtual string contact_person
        {
            get;
            set;
        }
        [DataMember]
        public virtual string created_by
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> create_time
        {
            get;
            set;
        }
        [DataMember]
        public virtual string updated_by
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> update_time
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual iom_organizations iom_organizations
        {
            get { return _iom_organizations; }
            set
            {
                if (!ReferenceEquals(_iom_organizations, value))
                {
                    var previousValue = _iom_organizations;
                    _iom_organizations = value;
                    Fixupiom_organizations(previousValue);
                }
            }
        }
        private iom_organizations _iom_organizations;
        
    
        [DataMember]
        public virtual lkp_assistance_type lkp_assistance_type
        {
            get { return _lkp_assistance_type; }
            set
            {
                if (!ReferenceEquals(_lkp_assistance_type, value))
                {
                    var previousValue = _lkp_assistance_type;
                    _lkp_assistance_type = value;
                    Fixuplkp_assistance_type(previousValue);
                }
            }
        }
        private lkp_assistance_type _lkp_assistance_type;
        
    
        [DataMember]
        public virtual iom_ward_profile iom_ward_profile
        {
            get { return _iom_ward_profile; }
            set
            {
                if (!ReferenceEquals(_iom_ward_profile, value))
                {
                    var previousValue = _iom_ward_profile;
                    _iom_ward_profile = value;
                    Fixupiom_ward_profile(previousValue);
                }
            }
        }
        private iom_ward_profile _iom_ward_profile;

        #endregion
        #region Association Fixup
    
        private void Fixupiom_organizations(iom_organizations previousValue)
        {
            if (previousValue != null && previousValue.iom_b2f_organizations_assisting.Contains(this))
            {
                previousValue.iom_b2f_organizations_assisting.Remove(this);
            }
    
            if (iom_organizations != null)
            {
                if (!iom_organizations.iom_b2f_organizations_assisting.Contains(this))
                {
                    iom_organizations.iom_b2f_organizations_assisting.Add(this);
                }
                if (organization != iom_organizations.id)
                {
                    organization = iom_organizations.id;
                }
            }
        }
    
        private void Fixuplkp_assistance_type(lkp_assistance_type previousValue)
        {
            if (previousValue != null && previousValue.iom_b2f_organizations_assisting.Contains(this))
            {
                previousValue.iom_b2f_organizations_assisting.Remove(this);
            }
    
            if (lkp_assistance_type != null)
            {
                if (!lkp_assistance_type.iom_b2f_organizations_assisting.Contains(this))
                {
                    lkp_assistance_type.iom_b2f_organizations_assisting.Add(this);
                }
                if (assistance_type != lkp_assistance_type.id)
                {
                    assistance_type = lkp_assistance_type.id;
                }
            }
        }
    
        private void Fixupiom_ward_profile(iom_ward_profile previousValue)
        {
            if (previousValue != null && previousValue.iom_b2f_organizations_assisting.Contains(this))
            {
                previousValue.iom_b2f_organizations_assisting.Remove(this);
            }
    
            if (iom_ward_profile != null)
            {
                if (!iom_ward_profile.iom_b2f_organizations_assisting.Contains(this))
                {
                    iom_ward_profile.iom_b2f_organizations_assisting.Add(this);
                }
                if (ward_profile_id != iom_ward_profile.id)
                {
                    ward_profile_id = iom_ward_profile.id;
                }
            }
        }

        #endregion
    }
}
