//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;
using DTM_Nigeria.Validation;

namespace DTM_Nigeria.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(iom_ga_gender_age_sample))]
    [KnownType(typeof(iom_ga_idp_population))]
    [KnownType(typeof(iom_ga_informants))]
    [KnownType(typeof(iom_ga_site_information))]
    [KnownType(typeof(iom_researchers))]
    [KnownType(typeof(lkp_Lga))]
    [KnownType(typeof(lkp_Period2))]
    [KnownType(typeof(lkp_ReasonOfDisp))]
    [KnownType(typeof(lkp_Shelter))]
    [KnownType(typeof(iom_group_assessment_2))]
    [KnownType(typeof(iom_ward_profile))]
    public partial class iom_group_assessment_1
    {
        #region Primitive Properties
        [DataMember]
        public virtual int id
        {
            get;
            set;
        }
        [DataMember]
        public virtual int b2f
        {
            get { return _b2f; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_b2f != value)
                    {
                        if (iom_ward_profile != null && iom_ward_profile.id != value)
                        {
                            iom_ward_profile = null;
                        }
                        _b2f = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private int _b2f;
        [DataMember]
        [Required(ErrorMessage = "*",AllowEmptyStrings=false)]
        public virtual string group_id
        {
            get;
            set;
        }
        [DataMember]
        [Required(ErrorMessage = "*", AllowEmptyStrings = false)]
        public virtual string location
        {
            get;
            set;
        }

        [DataMember]
        [RegularExpression("^[-]?[0-9]+(\\.[0-9]+)?", ErrorMessage = "decimal")]
        public virtual Nullable<double> coord_lon
        {
            get;
            set;
        }


        [DataMember]
        [RegularExpression("^[-]?[0-9]+(\\.[0-9]+)?", ErrorMessage = "decimal")]
        public virtual Nullable<double> coord_lat
        {
            get;
            set;
        }

        [DataMember]
        [Required(ErrorMessage = "*")]
        public virtual Nullable<System.DateTime> interview_date
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> researcher_id
        {
            get { return _researcher_id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_researcher_id != value)
                    {
                        if (iom_researchers != null && iom_researchers.id != value)
                        {
                            iom_researchers = null;
                        }
                        _researcher_id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _researcher_id;
        [DataMember]
        [Required(ErrorMessage = "*")]
        public virtual Nullable<int> shelter_type
        {
            get { return _shelter_type; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_shelter_type != value)
                    {
                        if (lkp_Shelter != null && lkp_Shelter.id != value)
                        {
                            lkp_Shelter = null;
                        }
                        _shelter_type = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _shelter_type;
        [DataMember]
        [RequiredIf("shelter_type", 8, "*")]
        public virtual string sheter_type_other
        {
            get;
            set;
        }

        [Required(ErrorMessage="*")]
        public string  state { get; set; }

        [DataMember]
        [Required(ErrorMessage="*")]
        public virtual string lga_orgin
        {
            get { return _lga_orgin; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_lga_orgin != value)
                    {
                        if (lkp_Lga != null && lkp_Lga.lga_code != value)
                        {
                            lkp_Lga = null;
                        }
                        _lga_orgin = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private string _lga_orgin;
        [DataMember]
        [Required(ErrorMessage="*")]
        public virtual Nullable<int> reason_for_disp
        {
            get { return _reason_for_disp; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_reason_for_disp != value)
                    {
                        if (lkp_ReasonOfDisp != null && lkp_ReasonOfDisp.id != value)
                        {
                            lkp_ReasonOfDisp = null;
                        }
                        _reason_for_disp = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _reason_for_disp;
        [DataMember]
        [RequiredIf("reason_for_disp", 4, "*")]
        public virtual string reason_other
        {
            get;
            set;
        }
        [DataMember]
        [Required(ErrorMessage="*")]
        [RegularExpression("^[1-9]+[0-9]*", ErrorMessage = "number>0")]
        public virtual Nullable<int> number_hh
        {
            get;
            set;
        }
        [DataMember]
        [Required(ErrorMessage = "*")]
        [RegularExpression("^[1-9]+[0-9]*", ErrorMessage = "number>0")]
        public virtual Nullable<int> number_ind
        {
            get;
            set;
        }
        [DataMember]
        [Required(ErrorMessage = "*")]
        public virtual Nullable<int> wave_of_disp
        {
            get { return _wave_of_disp; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_wave_of_disp != value)
                    {
                        if (lkp_Period2 != null && lkp_Period2.id != value)
                        {
                            lkp_Period2 = null;
                        }
                        _wave_of_disp = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _wave_of_disp;
        [DataMember]
        [RequiredIf("wave_of_disp",12,"*")]
        public virtual string wave_if_other
        {
            get;
            set;
        }


        public bool b_number_hh { get {return number_hh<=20;}
            set { if (value) { ;} }
        }

        [DataMember]
        [RequiredIf("b_number_hh", true, "*")]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> m0_5
        {
            get;
            set;
        }
        [DataMember]
        [RequiredIf("b_number_hh", true, "*")]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> m5_14
        {
            get;
            set;
        }
        [DataMember]
        [RequiredIf("b_number_hh", true, "*")]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> m15_24
        {
            get;
            set;
        }
        [DataMember]
        [RequiredIf("b_number_hh", true, "*")]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> m25_59
        {
            get;
            set;
        }
        [DataMember]
        [RequiredIf("b_number_hh", true, "*")]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> m60p
        {
            get;
            set;
        }
        [DataMember]
        [RequiredIf("b_number_hh", true, "*")]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> f0_5
        {
            get;
            set;
        }
        [DataMember]
        [RequiredIf("b_number_hh", true, "*")]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> f5_14
        {
            get;
            set;
        }
        [DataMember]
        [RequiredIf("b_number_hh", true, "*")]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> f15_24
        {
            get;
            set;
        }
        [DataMember]
        [RequiredIf("b_number_hh", true, "*")]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> f25_59
        {
            get;
            set;
        }
        [DataMember]
        [RequiredIf("b_number_hh", true, "*")]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> f60p
        {
            get;
            set;
        }
        [DataMember]
        [Required(ErrorMessage = "*")]
        [Range(4,16,ErrorMessage="4-16")]
        public virtual Nullable<int> credibility_rating
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> create_time
        {
            get;
            set;
        }
        [DataMember]
        public virtual string created_by
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> update_time
        {
            get;
            set;
        }
        [DataMember]
        public virtual string updated_by
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual ICollection<iom_ga_gender_age_sample> iom_ga_gender_age_sample
        {
            get
            {
                if (_iom_ga_gender_age_sample == null)
                {
                    var newCollection = new FixupCollection<iom_ga_gender_age_sample>();
                    newCollection.CollectionChanged += Fixupiom_ga_gender_age_sample;
                    _iom_ga_gender_age_sample = newCollection;
                }
                return _iom_ga_gender_age_sample;
            }
            set
            {
                if (!ReferenceEquals(_iom_ga_gender_age_sample, value))
                {
                    var previousValue = _iom_ga_gender_age_sample as FixupCollection<iom_ga_gender_age_sample>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_ga_gender_age_sample;
                    }
                    _iom_ga_gender_age_sample = value;
                    var newValue = value as FixupCollection<iom_ga_gender_age_sample>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_ga_gender_age_sample;
                    }
                }
            }
        }
        private ICollection<iom_ga_gender_age_sample> _iom_ga_gender_age_sample;
        
    
        [DataMember]
        public virtual ICollection<iom_ga_idp_population> iom_ga_idp_population
        {
            get
            {
                if (_iom_ga_idp_population == null)
                {
                    var newCollection = new FixupCollection<iom_ga_idp_population>();
                    newCollection.CollectionChanged += Fixupiom_ga_idp_population;
                    _iom_ga_idp_population = newCollection;
                }
                return _iom_ga_idp_population;
            }
            set
            {
                if (!ReferenceEquals(_iom_ga_idp_population, value))
                {
                    var previousValue = _iom_ga_idp_population as FixupCollection<iom_ga_idp_population>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_ga_idp_population;
                    }
                    _iom_ga_idp_population = value;
                    var newValue = value as FixupCollection<iom_ga_idp_population>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_ga_idp_population;
                    }
                }
            }
        }
        private ICollection<iom_ga_idp_population> _iom_ga_idp_population;
        
    
        [DataMember]
        public virtual ICollection<iom_ga_informants> iom_ga_informants
        {
            get
            {
                if (_iom_ga_informants == null)
                {
                    var newCollection = new FixupCollection<iom_ga_informants>();
                    newCollection.CollectionChanged += Fixupiom_ga_informants;
                    _iom_ga_informants = newCollection;
                }
                return _iom_ga_informants;
            }
            set
            {
                if (!ReferenceEquals(_iom_ga_informants, value))
                {
                    var previousValue = _iom_ga_informants as FixupCollection<iom_ga_informants>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_ga_informants;
                    }
                    _iom_ga_informants = value;
                    var newValue = value as FixupCollection<iom_ga_informants>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_ga_informants;
                    }
                }
            }
        }
        private ICollection<iom_ga_informants> _iom_ga_informants;
        
    
        [DataMember]
        public virtual ICollection<iom_ga_site_information> iom_ga_site_information
        {
            get
            {
                if (_iom_ga_site_information == null)
                {
                    var newCollection = new FixupCollection<iom_ga_site_information>();
                    newCollection.CollectionChanged += Fixupiom_ga_site_information;
                    _iom_ga_site_information = newCollection;
                }
                return _iom_ga_site_information;
            }
            set
            {
                if (!ReferenceEquals(_iom_ga_site_information, value))
                {
                    var previousValue = _iom_ga_site_information as FixupCollection<iom_ga_site_information>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_ga_site_information;
                    }
                    _iom_ga_site_information = value;
                    var newValue = value as FixupCollection<iom_ga_site_information>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_ga_site_information;
                    }
                }
            }
        }
        private ICollection<iom_ga_site_information> _iom_ga_site_information;
        
    
        [DataMember]
        public virtual iom_researchers iom_researchers
        {
            get { return _iom_researchers; }
            set
            {
                if (!ReferenceEquals(_iom_researchers, value))
                {
                    var previousValue = _iom_researchers;
                    _iom_researchers = value;
                    Fixupiom_researchers(previousValue);
                }
            }
        }
        private iom_researchers _iom_researchers;
        
    
        [DataMember]
        public virtual lkp_Lga lkp_Lga
        {
            get { return _lkp_Lga; }
            set
            {
                if (!ReferenceEquals(_lkp_Lga, value))
                {
                    var previousValue = _lkp_Lga;
                    _lkp_Lga = value;
                    Fixuplkp_Lga(previousValue);
                }
            }
        }
        private lkp_Lga _lkp_Lga;
        
    
        [DataMember]
        public virtual lkp_Period2 lkp_Period2
        {
            get { return _lkp_Period2; }
            set
            {
                if (!ReferenceEquals(_lkp_Period2, value))
                {
                    var previousValue = _lkp_Period2;
                    _lkp_Period2 = value;
                    Fixuplkp_Period2(previousValue);
                }
            }
        }
        private lkp_Period2 _lkp_Period2;
        
    
        [DataMember]
        public virtual lkp_ReasonOfDisp lkp_ReasonOfDisp
        {
            get { return _lkp_ReasonOfDisp; }
            set
            {
                if (!ReferenceEquals(_lkp_ReasonOfDisp, value))
                {
                    var previousValue = _lkp_ReasonOfDisp;
                    _lkp_ReasonOfDisp = value;
                    Fixuplkp_ReasonOfDisp(previousValue);
                }
            }
        }
        private lkp_ReasonOfDisp _lkp_ReasonOfDisp;
        
    
        [DataMember]
        public virtual lkp_Shelter lkp_Shelter
        {
            get { return _lkp_Shelter; }
            set
            {
                if (!ReferenceEquals(_lkp_Shelter, value))
                {
                    var previousValue = _lkp_Shelter;
                    _lkp_Shelter = value;
                    Fixuplkp_Shelter(previousValue);
                }
            }
        }
        private lkp_Shelter _lkp_Shelter;
        
    
        [DataMember]
        public virtual iom_group_assessment_2 iom_group_assessment_2
        {
            get { return _iom_group_assessment_2; }
            set
            {
                if (!ReferenceEquals(_iom_group_assessment_2, value))
                {
                    var previousValue = _iom_group_assessment_2;
                    _iom_group_assessment_2 = value;
                    Fixupiom_group_assessment_2(previousValue);
                }
            }
        }
        private iom_group_assessment_2 _iom_group_assessment_2;
        
    
        [DataMember]
        public virtual iom_ward_profile iom_ward_profile
        {
            get { return _iom_ward_profile; }
            set
            {
                if (!ReferenceEquals(_iom_ward_profile, value))
                {
                    var previousValue = _iom_ward_profile;
                    _iom_ward_profile = value;
                    Fixupiom_ward_profile(previousValue);
                }
            }
        }
        private iom_ward_profile _iom_ward_profile;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixupiom_researchers(iom_researchers previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_1.Contains(this))
            {
                previousValue.iom_group_assessment_1.Remove(this);
            }
    
            if (iom_researchers != null)
            {
                if (!iom_researchers.iom_group_assessment_1.Contains(this))
                {
                    iom_researchers.iom_group_assessment_1.Add(this);
                }
                if (researcher_id != iom_researchers.id)
                {
                    researcher_id = iom_researchers.id;
                }
            }
            else if (!_settingFK)
            {
                researcher_id = null;
            }
        }
    
        private void Fixuplkp_Lga(lkp_Lga previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_1.Contains(this))
            {
                previousValue.iom_group_assessment_1.Remove(this);
            }
    
            if (lkp_Lga != null)
            {
                if (!lkp_Lga.iom_group_assessment_1.Contains(this))
                {
                    lkp_Lga.iom_group_assessment_1.Add(this);
                }
                if (lga_orgin != lkp_Lga.lga_code)
                {
                    lga_orgin = lkp_Lga.lga_code;
                }
            }
            else if (!_settingFK)
            {
                lga_orgin = null;
            }
        }
    
        private void Fixuplkp_Period2(lkp_Period2 previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_1.Contains(this))
            {
                previousValue.iom_group_assessment_1.Remove(this);
            }
    
            if (lkp_Period2 != null)
            {
                if (!lkp_Period2.iom_group_assessment_1.Contains(this))
                {
                    lkp_Period2.iom_group_assessment_1.Add(this);
                }
                if (wave_of_disp != lkp_Period2.id)
                {
                    wave_of_disp = lkp_Period2.id;
                }
            }
            else if (!_settingFK)
            {
                wave_of_disp = null;
            }
        }
    
        private void Fixuplkp_ReasonOfDisp(lkp_ReasonOfDisp previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_1.Contains(this))
            {
                previousValue.iom_group_assessment_1.Remove(this);
            }
    
            if (lkp_ReasonOfDisp != null)
            {
                if (!lkp_ReasonOfDisp.iom_group_assessment_1.Contains(this))
                {
                    lkp_ReasonOfDisp.iom_group_assessment_1.Add(this);
                }
                if (reason_for_disp != lkp_ReasonOfDisp.id)
                {
                    reason_for_disp = lkp_ReasonOfDisp.id;
                }
            }
            else if (!_settingFK)
            {
                reason_for_disp = null;
            }
        }
    
        private void Fixuplkp_Shelter(lkp_Shelter previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_1.Contains(this))
            {
                previousValue.iom_group_assessment_1.Remove(this);
            }
    
            if (lkp_Shelter != null)
            {
                if (!lkp_Shelter.iom_group_assessment_1.Contains(this))
                {
                    lkp_Shelter.iom_group_assessment_1.Add(this);
                }
                if (shelter_type != lkp_Shelter.id)
                {
                    shelter_type = lkp_Shelter.id;
                }
            }
            else if (!_settingFK)
            {
                shelter_type = null;
            }
        }
    
        private void Fixupiom_group_assessment_2(iom_group_assessment_2 previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.iom_group_assessment_1, this))
            {
                previousValue.iom_group_assessment_1 = null;
            }
    
            if (iom_group_assessment_2 != null)
            {
                iom_group_assessment_2.iom_group_assessment_1 = this;
            }
        }
    
        private void Fixupiom_ward_profile(iom_ward_profile previousValue)
        {
            if (previousValue != null && previousValue.iom_group_assessment_1.Contains(this))
            {
                previousValue.iom_group_assessment_1.Remove(this);
            }
    
            if (iom_ward_profile != null)
            {
                if (!iom_ward_profile.iom_group_assessment_1.Contains(this))
                {
                    iom_ward_profile.iom_group_assessment_1.Add(this);
                }
                if (b2f != iom_ward_profile.id)
                {
                    b2f = iom_ward_profile.id;
                }
            }
        }
    
        private void Fixupiom_ga_gender_age_sample(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_ga_gender_age_sample item in e.NewItems)
                {
                    item.iom_group_assessment_1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_ga_gender_age_sample item in e.OldItems)
                {
                    if (ReferenceEquals(item.iom_group_assessment_1, this))
                    {
                        item.iom_group_assessment_1 = null;
                    }
                }
            }
        }
    
        private void Fixupiom_ga_idp_population(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_ga_idp_population item in e.NewItems)
                {
                    item.iom_group_assessment_1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_ga_idp_population item in e.OldItems)
                {
                    if (ReferenceEquals(item.iom_group_assessment_1, this))
                    {
                        item.iom_group_assessment_1 = null;
                    }
                }
            }
        }
    
        private void Fixupiom_ga_informants(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_ga_informants item in e.NewItems)
                {
                    item.iom_group_assessment_1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_ga_informants item in e.OldItems)
                {
                    if (ReferenceEquals(item.iom_group_assessment_1, this))
                    {
                        item.iom_group_assessment_1 = null;
                    }
                }
            }
        }
    
        private void Fixupiom_ga_site_information(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_ga_site_information item in e.NewItems)
                {
                    item.iom_group_assessment_1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_ga_site_information item in e.OldItems)
                {
                    if (ReferenceEquals(item.iom_group_assessment_1, this))
                    {
                        item.iom_group_assessment_1 = null;
                    }
                }
            }
        }

        #endregion
    }
}
