//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class iom_informants
    {
        public iom_informants()
        {
            this.iom_b1f_informants = new HashSet<iom_b1f_informants>();
            this.iom_b2f_informants = new HashSet<iom_b2f_informants>();
            this.iom_ga_informants = new HashSet<iom_ga_informants>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> type { get; set; }
        public string sex { get; set; }
        public string details { get; set; }
    
        public virtual ICollection<iom_b1f_informants> iom_b1f_informants { get; set; }
        public virtual ICollection<iom_b2f_informants> iom_b2f_informants { get; set; }
        public virtual ICollection<iom_ga_informants> iom_ga_informants { get; set; }
        public virtual lkp_Informant_Type lkp_Informant_Type { get; set; }
        public virtual lkp_Sex lkp_Sex { get; set; }
    }
    
}
