//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class iom_group_assessment_1
    {
        public iom_group_assessment_1()
        {
            this.iom_ga_gender_age_sample = new HashSet<iom_ga_gender_age_sample>();
            this.iom_ga_idp_population = new HashSet<iom_ga_idp_population>();
            this.iom_ga_informants = new HashSet<iom_ga_informants>();
            this.iom_ga_site_information = new HashSet<iom_ga_site_information>();
        }
    
        public int id { get; set; }
        public int b2f { get; set; }
        public string group_id { get; set; }
        public string location { get; set; }
        public Nullable<double> coord_lon { get; set; }
        public Nullable<double> coord_lat { get; set; }
        public Nullable<System.DateTime> interview_date { get; set; }
        public Nullable<int> researcher_id { get; set; }
        public Nullable<int> shelter_type { get; set; }
        public string sheter_type_other { get; set; }
        public string lga_orgin { get; set; }
        public Nullable<int> reason_for_disp { get; set; }
        public string reason_other { get; set; }
        public Nullable<int> number_hh { get; set; }
        public Nullable<int> number_ind { get; set; }
        public Nullable<int> wave_of_disp { get; set; }
        public string wave_if_other { get; set; }
        public Nullable<int> m0_5 { get; set; }
        public Nullable<int> m5_14 { get; set; }
        public Nullable<int> m15_24 { get; set; }
        public Nullable<int> m25_59 { get; set; }
        public Nullable<int> m60p { get; set; }
        public Nullable<int> f0_5 { get; set; }
        public Nullable<int> f5_14 { get; set; }
        public Nullable<int> f15_24 { get; set; }
        public Nullable<int> f25_59 { get; set; }
        public Nullable<int> f60p { get; set; }
        public Nullable<int> credibility_rating { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string updated_by { get; set; }
    
        public virtual ICollection<iom_ga_gender_age_sample> iom_ga_gender_age_sample { get; set; }
        public virtual ICollection<iom_ga_idp_population> iom_ga_idp_population { get; set; }
        public virtual ICollection<iom_ga_informants> iom_ga_informants { get; set; }
        public virtual ICollection<iom_ga_site_information> iom_ga_site_information { get; set; }
        public virtual iom_researchers iom_researchers { get; set; }
        public virtual iom_ward_profile iom_ward_profile { get; set; }
        public virtual lkp_Lga lkp_Lga { get; set; }
        public virtual lkp_Period2 lkp_Period2 { get; set; }
        public virtual lkp_ReasonOfDisp lkp_ReasonOfDisp { get; set; }
        public virtual lkp_Shelter lkp_Shelter { get; set; }
        public virtual iom_group_assessment_2 iom_group_assessment_2 { get; set; }
    }
    
}
