//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class iom_ga_gender_age_sample
    {
        public int hhs { get; set; }
        public int ga_id { get; set; }
        public Nullable<int> m_lt1 { get; set; }
        public Nullable<int> m_1_5 { get; set; }
        public Nullable<int> m_6_17 { get; set; }
        public Nullable<int> m_18_59 { get; set; }
        public Nullable<int> m_60p { get; set; }
        public Nullable<int> f_lt1 { get; set; }
        public Nullable<int> f_1_5 { get; set; }
        public Nullable<int> f_6_17 { get; set; }
        public Nullable<int> f_18_59 { get; set; }
        public Nullable<int> f_60p { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
    
        public virtual iom_group_assessment_1 iom_group_assessment_1 { get; set; }
    }
    
}
