//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

namespace DTM_Nigeria.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(iom_group_assessment_1))]
    public partial class iom_ga_gender_age_sample
    {
        #region Primitive Properties
        [DataMember]
        public virtual int hhs
        {
            get;
            set;
        }
        [DataMember]
        public virtual int ga_id
        {
            get { return _ga_id; }
            set
            {
                if (_ga_id != value)
                {
                    if (iom_group_assessment_1 != null && iom_group_assessment_1.id != value)
                    {
                        iom_group_assessment_1 = null;
                    }
                    _ga_id = value;
                }
            }
        }
        private int _ga_id;
        [DataMember]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> m_lt1
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> m_1_5
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> m_6_17
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> m_18_59
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> m_60p
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> f_lt1
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> f_1_5
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> f_6_17
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> f_18_59
        {
            get;
            set;
        }
        [DataMember]
        [RegularExpression("^[0-9]*", ErrorMessage = "*")]
        public virtual Nullable<int> f_60p
        {
            get;
            set;
        }
        [DataMember]
        public virtual string created_by
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> create_time
        {
            get;
            set;
        }
        [DataMember]
        public virtual string updated_by
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> update_time
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual iom_group_assessment_1 iom_group_assessment_1
        {
            get { return _iom_group_assessment_1; }
            set
            {
                if (!ReferenceEquals(_iom_group_assessment_1, value))
                {
                    var previousValue = _iom_group_assessment_1;
                    _iom_group_assessment_1 = value;
                    Fixupiom_group_assessment_1(previousValue);
                }
            }
        }
        private iom_group_assessment_1 _iom_group_assessment_1;

        #endregion
        #region Association Fixup
    
        private void Fixupiom_group_assessment_1(iom_group_assessment_1 previousValue)
        {
            if (previousValue != null && previousValue.iom_ga_gender_age_sample.Contains(this))
            {
                previousValue.iom_ga_gender_age_sample.Remove(this);
            }
    
            if (iom_group_assessment_1 != null)
            {
                if (!iom_group_assessment_1.iom_ga_gender_age_sample.Contains(this))
                {
                    iom_group_assessment_1.iom_ga_gender_age_sample.Add(this);
                }
                if (ga_id != iom_group_assessment_1.id)
                {
                    ga_id = iom_group_assessment_1.id;
                }
            }
        }

        #endregion
    }
}
