//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DTM_Nigeria.Models
{
    public partial class iom_ga_site_information
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ga_id
        {
            get { return _ga_id; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_ga_id != value)
                    {
                        if (iom_group_assessment_1 != null && iom_group_assessment_1.id != value)
                        {
                            iom_group_assessment_1 = null;
                        }
                        _ga_id = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _ga_id;
    
        public virtual string name_site
        {
            get;
            set;
        }
    
        public virtual Nullable<double> coord_lon
        {
            get;
            set;
        }
    
        public virtual Nullable<double> coord_lat
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> create_time
        {
            get;
            set;
        }
    
        public virtual string created_by
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> update_time
        {
            get;
            set;
        }
    
        public virtual string updated_by
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual iom_group_assessment_1 iom_group_assessment_1
        {
            get { return _iom_group_assessment_1; }
            set
            {
                if (!ReferenceEquals(_iom_group_assessment_1, value))
                {
                    var previousValue = _iom_group_assessment_1;
                    _iom_group_assessment_1 = value;
                    Fixupiom_group_assessment_1(previousValue);
                }
            }
        }
        private iom_group_assessment_1 _iom_group_assessment_1;

        #endregion
        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void Fixupiom_group_assessment_1(iom_group_assessment_1 previousValue)
        {
            if (previousValue != null && previousValue.iom_ga_site_information.Contains(this))
            {
                previousValue.iom_ga_site_information.Remove(this);
            }
    
            if (iom_group_assessment_1 != null)
            {
                if (!iom_group_assessment_1.iom_ga_site_information.Contains(this))
                {
                    iom_group_assessment_1.iom_ga_site_information.Add(this);
                }
                if (ga_id != iom_group_assessment_1.id)
                {
                    ga_id = iom_group_assessment_1.id;
                }
            }
            else if (!_settingFK)
            {
                ga_id = null;
            }
        }

        #endregion
    }
}
