//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class iom_ga_site_information
    {
        public int id { get; set; }
        public Nullable<int> ga_id { get; set; }
        public string name_site { get; set; }
        public Nullable<double> coord_lon { get; set; }
        public Nullable<double> coord_lat { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string updated_by { get; set; }
    
        public virtual iom_group_assessment_1 iom_group_assessment_1 { get; set; }
    }
    
}
