//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class iom_profile
    {
        public iom_profile()
        {
            this.iom_b1f_informants = new HashSet<iom_b1f_informants>();
            this.iom_b1f_organizations_assisting = new HashSet<iom_b1f_organizations_assisting>();
            this.iom_idp_arrival = new HashSet<iom_idp_arrival>();
            this.iom_presence_wards = new HashSet<iom_presence_wards>();
        }
    
        public int id { get; set; }
        public int phase { get; set; }
        public string date { get; set; }
        public int researcher_id { get; set; }
        public string lga { get; set; }
        public string settlement { get; set; }
        public string settlement_type { get; set; }
        public int displaced_hh_ind_YesNo { get; set; }
        public Nullable<int> number_hh { get; set; }
        public Nullable<int> number_ind { get; set; }
        public int nr_YesNo { get; set; }
        public string nr_location { get; set; }
        public string nr_state1 { get; set; }
        public string nr_state2 { get; set; }
        public Nullable<int> nr_period { get; set; }
        public int reason_insurgency_YesNo { get; set; }
        public Nullable<int> reason_insurg_year { get; set; }
        public Nullable<int> reason_insurg_hh { get; set; }
        public Nullable<int> reason_insurg_ind { get; set; }
        public int reason_clash_YesNo { get; set; }
        public Nullable<int> reason_clash_year { get; set; }
        public Nullable<int> reason_clash_hh { get; set; }
        public Nullable<int> reason_clash_ind { get; set; }
        public int reason_disaster_YesNo { get; set; }
        public Nullable<int> reason_disaster_year { get; set; }
        public Nullable<int> reason_disaster_hh { get; set; }
        public Nullable<int> reason_disaster_ind { get; set; }
        public int reason_others_YesNo { get; set; }
        public string reason_others_name { get; set; }
        public Nullable<int> reason_others_year { get; set; }
        public Nullable<int> reason_others_hh { get; set; }
        public Nullable<int> reason_others_ind { get; set; }
        public int temporary_settlement_type_camp_YesNo { get; set; }
        public Nullable<int> temporary_settlement_hh_camp { get; set; }
        public Nullable<int> temporary_settlement_ind_camp { get; set; }
        public int temporary_settlement_type_hc_YesNo { get; set; }
        public Nullable<int> temporary_settlement_hh_hc { get; set; }
        public Nullable<int> temporary_settlement_ind_hc { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
    
        public virtual ICollection<iom_b1f_informants> iom_b1f_informants { get; set; }
        public virtual ICollection<iom_b1f_organizations_assisting> iom_b1f_organizations_assisting { get; set; }
        public virtual iom_dtm_phase iom_dtm_phase { get; set; }
        public virtual ICollection<iom_idp_arrival> iom_idp_arrival { get; set; }
        public virtual ICollection<iom_presence_wards> iom_presence_wards { get; set; }
        public virtual iom_researchers iom_researchers { get; set; }
        public virtual lkp_Lga lkp_Lga { get; set; }
        public virtual lkp_NotReturnLocation lkp_NotReturnLocation { get; set; }
        public virtual lkp_Period2 lkp_Period2 { get; set; }
        public virtual lkp_Period2 lkp_Period21 { get; set; }
        public virtual lkp_Period2 lkp_Period22 { get; set; }
        public virtual lkp_Period2 lkp_Period23 { get; set; }
        public virtual lkp_Period2 lkp_Period24 { get; set; }
        public virtual lkp_Settlement lkp_Settlement { get; set; }
        public virtual lkp_State lkp_State { get; set; }
        public virtual lkp_State lkp_State1 { get; set; }
    }
    
}
