//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using System.ComponentModel.DataAnnotations;

namespace DTM_Nigeria.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(iom_informants))]
    [KnownType(typeof(iom_group_assessment_1))]
    public partial class iom_ga_informants
    {
        #region Primitive Properties
        [DataMember]
        public virtual int id
        {
            get;
            set;
        }

        [Required]
        public bool notEmpty { get; set; }

        [DataMember]
        public virtual int ga_id
        {
            get { return _ga_id; }
            set
            {
                if (_ga_id != value)
                {
                    if (iom_group_assessment_1 != null && iom_group_assessment_1.id != value)
                    {
                        iom_group_assessment_1 = null;
                    }
                    _ga_id = value;
                }
            }
        }
        private int _ga_id;
        [DataMember]
        public virtual int informant
        {
            get { return _informant; }
            set
            {
                if (_informant != value)
                {
                    if (iom_informants != null && iom_informants.id != value)
                    {
                        iom_informants = null;
                    }
                    _informant = value;
                }
            }
        }
        private int _informant;
        [DataMember]
        public virtual string created_by
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> create_time
        {
            get;
            set;
        }
        [DataMember]
        public virtual string updated_by
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> update_time
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
        
    
        [DataMember]
        public virtual iom_informants iom_informants
        {
            get { return _iom_informants; }
            set
            {
                if (!ReferenceEquals(_iom_informants, value))
                {
                    var previousValue = _iom_informants;
                    _iom_informants = value;
                    Fixupiom_informants(previousValue);
                }
            }
        }
        private iom_informants _iom_informants;
        
    
        [DataMember]
        public virtual iom_group_assessment_1 iom_group_assessment_1
        {
            get { return _iom_group_assessment_1; }
            set
            {
                if (!ReferenceEquals(_iom_group_assessment_1, value))
                {
                    var previousValue = _iom_group_assessment_1;
                    _iom_group_assessment_1 = value;
                    Fixupiom_group_assessment_1(previousValue);
                }
            }
        }
        private iom_group_assessment_1 _iom_group_assessment_1;

        #endregion
        #region Association Fixup
    
        private void Fixupiom_informants(iom_informants previousValue)
        {
            if (previousValue != null && previousValue.iom_ga_informants.Contains(this))
            {
                previousValue.iom_ga_informants.Remove(this);
            }
    
            if (iom_informants != null)
            {
                if (!iom_informants.iom_ga_informants.Contains(this))
                {
                    iom_informants.iom_ga_informants.Add(this);
                }
                if (informant != iom_informants.id)
                {
                    informant = iom_informants.id;
                }
            }
        }
    
        private void Fixupiom_group_assessment_1(iom_group_assessment_1 previousValue)
        {
            if (previousValue != null && previousValue.iom_ga_informants.Contains(this))
            {
                previousValue.iom_ga_informants.Remove(this);
            }
    
            if (iom_group_assessment_1 != null)
            {
                if (!iom_group_assessment_1.iom_ga_informants.Contains(this))
                {
                    iom_group_assessment_1.iom_ga_informants.Add(this);
                }
                if (ga_id != iom_group_assessment_1.id)
                {
                    ga_id = iom_group_assessment_1.id;
                }
            }
        }

        #endregion
    }
}
