//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class iom_ward_presence_per_location
    {
        public int id { get; set; }
        public int ward_profile_id { get; set; }
        public string location_name { get; set; }
        public string location_type { get; set; }
        public int idp_category { get; set; }
        public Nullable<int> MainUnfulfilledNeed { get; set; }
        public int idp_registered_list_YesNo { get; set; }
        public string registered_by { get; set; }
        public int estimate_ind { get; set; }
        public string majority_stateoforigin { get; set; }
        public string majority_lgaoforigin { get; set; }
        public Nullable<double> coord_lon { get; set; }
        public Nullable<double> coord_lat { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> update_time { get; set; }
        public bool entered_in_SA { get; set; }
        public Nullable<int> estimate_hh { get; set; }
    
        public virtual iom_ward_profile iom_ward_profile { get; set; }
        public virtual lkp_IDP_Category lkp_IDP_Category { get; set; }
        public virtual lkp_Lga lkp_Lga { get; set; }
        public virtual lkp_MainUnfulfilledNeed lkp_MainUnfulfilledNeed { get; set; }
        public virtual lkp_State lkp_State { get; set; }
        public virtual lkp_TypeOfResidence lkp_TypeOfResidence { get; set; }
    }
    
}
