//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class lkp_Ethnicity
    {
        public lkp_Ethnicity()
        {
            this.iom_ga_idp_population = new HashSet<iom_ga_idp_population>();
        }
    
        public int id { get; set; }
        public string value { get; set; }
    
        public virtual ICollection<iom_ga_idp_population> iom_ga_idp_population { get; set; }
    }
    
}
