//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class lkp_Sex
    {
        public lkp_Sex()
        {
            this.iom_informants = new HashSet<iom_informants>();
        }
    
        public string id { get; set; }
        public string sex { get; set; }
    
        public virtual ICollection<iom_informants> iom_informants { get; set; }
    }
    
}
