//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class lkp_State
    {
        public lkp_State()
        {
            this.iom_idp_arrival = new HashSet<iom_idp_arrival>();
            this.iom_presence_wards = new HashSet<iom_presence_wards>();
            this.iom_profile = new HashSet<iom_profile>();
            this.iom_profile1 = new HashSet<iom_profile>();
            this.iom_ward_idp_arrival = new HashSet<iom_ward_idp_arrival>();
            this.iom_ward_presence_per_location = new HashSet<iom_ward_presence_per_location>();
            this.iom_ward_profile = new HashSet<iom_ward_profile>();
            this.iom_ward_profile1 = new HashSet<iom_ward_profile>();
            this.iom_ward_profile2 = new HashSet<iom_ward_profile>();
            this.iom_ward_profile3 = new HashSet<iom_ward_profile>();
            this.iom_ward_profile4 = new HashSet<iom_ward_profile>();
            this.iom_ward_profile5 = new HashSet<iom_ward_profile>();
            this.iom_ward_profile6 = new HashSet<iom_ward_profile>();
            this.lkp_Lga = new HashSet<lkp_Lga>();
        }
    
        public int id { get; set; }
        public string state_name { get; set; }
        public string state_code { get; set; }
    
        public virtual ICollection<iom_idp_arrival> iom_idp_arrival { get; set; }
        public virtual ICollection<iom_presence_wards> iom_presence_wards { get; set; }
        public virtual ICollection<iom_profile> iom_profile { get; set; }
        public virtual ICollection<iom_profile> iom_profile1 { get; set; }
        public virtual ICollection<iom_ward_idp_arrival> iom_ward_idp_arrival { get; set; }
        public virtual ICollection<iom_ward_presence_per_location> iom_ward_presence_per_location { get; set; }
        public virtual ICollection<iom_ward_profile> iom_ward_profile { get; set; }
        public virtual ICollection<iom_ward_profile> iom_ward_profile1 { get; set; }
        public virtual ICollection<iom_ward_profile> iom_ward_profile2 { get; set; }
        public virtual ICollection<iom_ward_profile> iom_ward_profile3 { get; set; }
        public virtual ICollection<iom_ward_profile> iom_ward_profile4 { get; set; }
        public virtual ICollection<iom_ward_profile> iom_ward_profile5 { get; set; }
        public virtual ICollection<iom_ward_profile> iom_ward_profile6 { get; set; }
        public virtual ICollection<lkp_Lga> lkp_Lga { get; set; }
    }
    
}
