//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DTM_Nigeria.Models
{
    public partial class lkp_trust_ppl_degree
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string val
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<iom_ward_profile> iom_ward_profile
        {
            get
            {
                if (_iom_ward_profile == null)
                {
                    var newCollection = new FixupCollection<iom_ward_profile>();
                    newCollection.CollectionChanged += Fixupiom_ward_profile;
                    _iom_ward_profile = newCollection;
                }
                return _iom_ward_profile;
            }
            set
            {
                if (!ReferenceEquals(_iom_ward_profile, value))
                {
                    var previousValue = _iom_ward_profile as FixupCollection<iom_ward_profile>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_ward_profile;
                    }
                    _iom_ward_profile = value;
                    var newValue = value as FixupCollection<iom_ward_profile>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_ward_profile;
                    }
                }
            }
        }
        private ICollection<iom_ward_profile> _iom_ward_profile;
    
        public virtual ICollection<iom_ward_profile> iom_ward_profile1
        {
            get
            {
                if (_iom_ward_profile1 == null)
                {
                    var newCollection = new FixupCollection<iom_ward_profile>();
                    newCollection.CollectionChanged += Fixupiom_ward_profile1;
                    _iom_ward_profile1 = newCollection;
                }
                return _iom_ward_profile1;
            }
            set
            {
                if (!ReferenceEquals(_iom_ward_profile1, value))
                {
                    var previousValue = _iom_ward_profile1 as FixupCollection<iom_ward_profile>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_ward_profile1;
                    }
                    _iom_ward_profile1 = value;
                    var newValue = value as FixupCollection<iom_ward_profile>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_ward_profile1;
                    }
                }
            }
        }
        private ICollection<iom_ward_profile> _iom_ward_profile1;
    
        public virtual ICollection<iom_ward_profile> iom_ward_profile2
        {
            get
            {
                if (_iom_ward_profile2 == null)
                {
                    var newCollection = new FixupCollection<iom_ward_profile>();
                    newCollection.CollectionChanged += Fixupiom_ward_profile2;
                    _iom_ward_profile2 = newCollection;
                }
                return _iom_ward_profile2;
            }
            set
            {
                if (!ReferenceEquals(_iom_ward_profile2, value))
                {
                    var previousValue = _iom_ward_profile2 as FixupCollection<iom_ward_profile>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_ward_profile2;
                    }
                    _iom_ward_profile2 = value;
                    var newValue = value as FixupCollection<iom_ward_profile>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_ward_profile2;
                    }
                }
            }
        }
        private ICollection<iom_ward_profile> _iom_ward_profile2;

        #endregion
        #region Association Fixup
    
        private void Fixupiom_ward_profile(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_ward_profile item in e.NewItems)
                {
                    item.lkp_trust_ppl_degree = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_ward_profile item in e.OldItems)
                {
                    if (ReferenceEquals(item.lkp_trust_ppl_degree, this))
                    {
                        item.lkp_trust_ppl_degree = null;
                    }
                }
            }
        }
    
        private void Fixupiom_ward_profile1(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_ward_profile item in e.NewItems)
                {
                    item.lkp_trust_ppl_degree1 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_ward_profile item in e.OldItems)
                {
                    if (ReferenceEquals(item.lkp_trust_ppl_degree1, this))
                    {
                        item.lkp_trust_ppl_degree1 = null;
                    }
                }
            }
        }
    
        private void Fixupiom_ward_profile2(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_ward_profile item in e.NewItems)
                {
                    item.lkp_trust_ppl_degree2 = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_ward_profile item in e.OldItems)
                {
                    if (ReferenceEquals(item.lkp_trust_ppl_degree2, this))
                    {
                        item.lkp_trust_ppl_degree2 = null;
                    }
                }
            }
        }

        #endregion
    }
}
