//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DTM_Nigeria.Models
{
    public partial class lkp_Religion
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string value
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<iom_ga_idp_population> iom_ga_idp_population
        {
            get
            {
                if (_iom_ga_idp_population == null)
                {
                    var newCollection = new FixupCollection<iom_ga_idp_population>();
                    newCollection.CollectionChanged += Fixupiom_ga_idp_population;
                    _iom_ga_idp_population = newCollection;
                }
                return _iom_ga_idp_population;
            }
            set
            {
                if (!ReferenceEquals(_iom_ga_idp_population, value))
                {
                    var previousValue = _iom_ga_idp_population as FixupCollection<iom_ga_idp_population>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupiom_ga_idp_population;
                    }
                    _iom_ga_idp_population = value;
                    var newValue = value as FixupCollection<iom_ga_idp_population>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupiom_ga_idp_population;
                    }
                }
            }
        }
        private ICollection<iom_ga_idp_population> _iom_ga_idp_population;

        #endregion
        #region Association Fixup
    
        private void Fixupiom_ga_idp_population(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (iom_ga_idp_population item in e.NewItems)
                {
                    item.lkp_Religion = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (iom_ga_idp_population item in e.OldItems)
                {
                    if (ReferenceEquals(item.lkp_Religion, this))
                    {
                        item.lkp_Religion = null;
                    }
                }
            }
        }

        #endregion
    }
}
