//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class lkp_trust_ppl_degree
    {
        public lkp_trust_ppl_degree()
        {
            this.iom_ward_profile = new HashSet<iom_ward_profile>();
            this.iom_ward_profile1 = new HashSet<iom_ward_profile>();
            this.iom_ward_profile2 = new HashSet<iom_ward_profile>();
        }
    
        public int id { get; set; }
        public string val { get; set; }
    
        public virtual ICollection<iom_ward_profile> iom_ward_profile { get; set; }
        public virtual ICollection<iom_ward_profile> iom_ward_profile1 { get; set; }
        public virtual ICollection<iom_ward_profile> iom_ward_profile2 { get; set; }
    }
    
}
