//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class lkp_Ward
    {
        public lkp_Ward()
        {
            this.iom_ga_idp_population = new HashSet<iom_ga_idp_population>();
            this.iom_group_assessment_2 = new HashSet<iom_group_assessment_2>();
            this.iom_presence_wards = new HashSet<iom_presence_wards>();
            this.iom_ward_profile = new HashSet<iom_ward_profile>();
            this.iom_ward_profile1 = new HashSet<iom_ward_profile>();
            this.iom_ward_profile2 = new HashSet<iom_ward_profile>();
        }
    
        public int id { get; set; }
        public string lga_code { get; set; }
        public string ward_name { get; set; }
        public string ward_code { get; set; }
    
        public virtual ICollection<iom_ga_idp_population> iom_ga_idp_population { get; set; }
        public virtual ICollection<iom_group_assessment_2> iom_group_assessment_2 { get; set; }
        public virtual ICollection<iom_presence_wards> iom_presence_wards { get; set; }
        public virtual ICollection<iom_ward_profile> iom_ward_profile { get; set; }
        public virtual ICollection<iom_ward_profile> iom_ward_profile1 { get; set; }
        public virtual ICollection<iom_ward_profile> iom_ward_profile2 { get; set; }
        public virtual lkp_Lga lkp_Lga { get; set; }
    }
    
}
