//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DTM_Nigeria.Models
{
    public partial class view_estimate_hhs_Inds_per_Wards_per_Year_of_Arrival
    {
        #region Primitive Properties
    
        public virtual int phase
        {
            get;
            set;
        }
    
        public virtual string state_code
        {
            get;
            set;
        }
    
        public virtual string state_name
        {
            get;
            set;
        }
    
        public virtual string lga_code
        {
            get;
            set;
        }
    
        public virtual string lga_name
        {
            get;
            set;
        }
    
        public virtual string ward_code
        {
            get;
            set;
        }
    
        public virtual string ward_name
        {
            get;
            set;
        }
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual Nullable<int> estimate_hh_Ward
        {
            get;
            set;
        }
    
        public virtual Nullable<int> estimate_Ind_Ward
        {
            get;
            set;
        }
    
        public virtual string year_arrival
        {
            get;
            set;
        }
    
        public virtual Nullable<int> hh
        {
            get;
            set;
        }
    
        public virtual Nullable<int> ind
        {
            get;
            set;
        }

        #endregion
    }
}
