//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DTM_Nigeria.Models
{
    public partial class view_error_check_Camp_with_No_Figues_In_B2F
    {
        #region Primitive Properties
    
        public virtual int phase
        {
            get;
            set;
        }
    
        public virtual string state_name
        {
            get;
            set;
        }
    
        public virtual string lga_name
        {
            get;
            set;
        }
    
        public virtual string ward_name
        {
            get;
            set;
        }
    
        public virtual Nullable<int> hhs_Ward
        {
            get;
            set;
        }
    
        public virtual Nullable<int> inds_Ward
        {
            get;
            set;
        }

        #endregion
    }
}
