//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class view_error_check_HC_vs_Camp
    {
        public int phase { get; set; }
        public string state_name { get; set; }
        public string lga_name { get; set; }
        public string ward_name { get; set; }
        public Nullable<int> hhs { get; set; }
        public Nullable<int> inds { get; set; }
    }
    
}
