//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class view_error_check_Numbers_Ward_vs_B2F
    {
        public int phase { get; set; }
        public string state_name { get; set; }
        public string lga_name { get; set; }
        public string ward_name { get; set; }
        public int ward_id { get; set; }
        public int estimate_hh { get; set; }
        public int estimate_ind { get; set; }
        public Nullable<int> number_hh { get; set; }
        public Nullable<int> number_ind { get; set; }
    }
    
}
