//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class view_estimate_hhs_Inds_per_Wards
    {
        public int iom_profileId { get; set; }
        public int ward_profile_id { get; set; }
        public string date { get; set; }
        public int phase { get; set; }
        public string state_code { get; set; }
        public string state_name { get; set; }
        public string lga_code { get; set; }
        public string lga_name { get; set; }
        public string ward_code { get; set; }
        public string ward_name { get; set; }
        public int id { get; set; }
        public Nullable<int> estimate_hh_Ward { get; set; }
        public Nullable<int> estimate_Ind_Ward { get; set; }
        public string location_type { get; set; }
        public string Year { get; set; }
        public int idp_category { get; set; }
        public string majority_stateoforigin { get; set; }
        public string state_orig { get; set; }
        public string majority_lgaoforigin { get; set; }
        public string lga_orig { get; set; }
        public Nullable<int> reason_insurgency_YesNo { get; set; }
        public Nullable<int> reason_insurg_hh { get; set; }
        public Nullable<int> reason_insurg_ind { get; set; }
        public Nullable<int> reason_clash_YesNo { get; set; }
        public Nullable<int> reason_clash_hh { get; set; }
        public Nullable<int> reason_clash_ind { get; set; }
        public Nullable<int> reason_disaster_YesNo { get; set; }
        public Nullable<int> reason_disaster_hh { get; set; }
        public Nullable<int> reason_disaster_ind { get; set; }
        public Nullable<int> reason_others_YesNo { get; set; }
        public Nullable<int> reason_others_hh { get; set; }
        public Nullable<int> reason_others_ind { get; set; }
        public Nullable<int> NbHH_makeshift { get; set; }
        public Nullable<int> NbHH_overcrowded_houses { get; set; }
        public Nullable<int> NbHH_damaged_houses { get; set; }
        public Nullable<int> NbHH_living_outdoors { get; set; }
        public Nullable<int> NbHH_need_NFI { get; set; }
        public Nullable<int> NbHH_need_KitchenSet { get; set; }
        public Nullable<int> NbHH_need_Full_kits { get; set; }
    }
    
}
