//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace DTM_Nigeria.Models
{
    public partial class vw_error_ck_B2F_vs_LocA
    {
        public string state_code { get; set; }
        public string state_name { get; set; }
        public string lga_code { get; set; }
        public string lga_name { get; set; }
        public string ward_code { get; set; }
        public string ward_name { get; set; }
        public Nullable<int> hh { get; set; }
        public Nullable<int> ind { get; set; }
        public int phase { get; set; }
    }
    
}
